/**
 * The accessibility statement's words in Norwegian, Swedish, Danish and English (wave 1, 1e). HAND-WRITTEN, never
 * machine-translated, NOT legal advice, and every sentence needs human legal review before real use (docs/wave-1-trust.md
 * section 8): the conformity wording, the microenterprise sentence and the enforcement-body lines in particular. A table of
 * sentences with `{name}` holes; the shape (which sentence for which fact) is in `a11y-statement.ts`. A statement never
 * says the site "conforms" unless the owner has given an audit's assessor and date.
 */
import type { StarterLanguage } from "./legal-starters";

export type A11yText = { locale: string; m: Record<string, string> };

const EN: A11yText = {
  locale: "en-GB",
  m: {
    notice:
      "DRAFT: needs legal review before use. Kaizen Store made this text from your store's details and your answers as a starting point. It is not legal advice and no lawyer has checked it. Read every sentence, fill in the [[bracketed]] parts, and delete this notice when you have.",
    "notice.language": "This text is in English because it is not available in your store's language: have it translated and reviewed by a person before use.",
    "ph.add": "Add",
    "ph.check": "Check",
    "label.email": "contact email",
    "label.assessor": "who assessed the site",
    "label.siteAddress": "the website address",
    "label.storeName": "store name",
    "label.annex": "the information the European Accessibility Act asks for in a service provider's statement (Annex V)",
    "label.date": "date",
    "label.microenterprise": "that the business meets the conditions for a microenterprise, and how the exemption is worded in your country",
    "title": "Accessibility statement",
    "slug": "accessibility-statement",
    "h.status": "How accessible this website is",
    "a11y.status.not_assessed": "{store} has not assessed this website against accessibility requirements. We aim to build it to the Web Content Accessibility Guidelines (WCAG) 2.2, level AA, but we have not checked that it meets them, so we do not say that it does.",
    "a11y.status.partial": "This website partly conforms to the Web Content Accessibility Guidelines (WCAG) 2.2, level AA. Some parts do not yet meet them, as set out below.",
    "a11y.status.full": "This website conforms to the Web Content Accessibility Guidelines (WCAG) 2.2, level AA, as assessed below.",
    "a11y.status.note": "An automated check finds only some of the problems that can make a website hard to use. This statement is only as good as the assessment behind it.",
    "h.standard": "The standard we build to",
    "a11y.standard.1": "We build to WCAG 2.2 level AA. The harmonised European standard for accessibility of information and communication technology is EN 301 549, which refers to WCAG.",
    "h.assessment": "How this was assessed",
    "a11y.assessment.none": "No independent assessment has been made. The checks we run ourselves are listed under known issues.",
    "a11y.assessment.by": "Assessed by {by} on {on}.",
    "a11y.assessment.report": "The report is at {url}.",
    "a11y.assessment.note": "Assessment notes: {note}",
    "h.scope": "What this covers",
    "a11y.scope.1": "This statement covers the store's website at {addresses}.",
    "a11y.scope.2": "The website is available in: {languages}.",
    "h.known_issues": "Known issues",
    "a11y.issue.theme": "Colour combinations in the store's design below the recommended contrast of 4.5 to 1, so some text can be hard to read: {n}.",
    "a11y.issue.alt": "Pictures in the store's media library with no alt text: {missing} of {total}.",
    "a11y.issue.pages": "Published pages with problems the page checker flags as blocking, such as pictures without alt text or empty links: {n}.",
    "a11y.issue.own": "{text}",
    "a11y.issues.none": "We know of no issues beyond the parts from other providers described below. This does not mean there are none.",
    "h.third_party": "Parts from other providers",
    "a11y.third.1": "Payment is made in a form provided by Stripe, which we do not build. We have not assessed its accessibility ourselves.",
    "h.microenterprise": "Exemption for microenterprises",
    "a11y.micro.1": "The business has told us it is a microenterprise, with fewer than 10 staff and a turnover or balance sheet of at most EUR 2 million. Microenterprises that provide services are exempt from the accessibility requirements for services in the European Accessibility Act (Directive (EU) 2019/882, Article 4(5)). {check}",
    "h.feedback": "Tell us about a problem",
    "a11y.feedback.1": "If you find something on this website that you cannot use, write to us at {email}. Tell us the address of the page and what went wrong, and we will answer.",
    "a11y.annex": "{check}",
    "h.enforcement": "Where to complain",
    "a11y.enforcement.1": "If you are not satisfied with our answer, you can turn to the authority that supervises accessibility:",
    "a11y.enforcement.verified": "{country}: {body}.",
    "a11y.enforcement.unverified": "{country}: possibly {body}. This has not been verified: check with the authority.",
    "a11y.enforcement.other": "{country}: the national market surveillance authority for accessibility. The European Commission keeps a list of them. This has not been verified: check with the authority.",
    "a11y.note.NO": "Whether and how Norway has taken in the European Accessibility Act is not confirmed. The rules that apply to you in Norway: check with Digdir.",
    "h.prepared": "About this statement",
    "a11y.prepared.1": "This statement was prepared on {prepared}.",
    "a11y.prepared.2": "It was last reviewed on {reviewed}.",
  },
};

const NB: A11yText = {
  locale: "nb-NO",
  m: {
    notice:
      "UTKAST: må gjennomgås juridisk før bruk. Kaizen Store har laget denne teksten av butikkens opplysninger og svarene dine som et utgangspunkt. Den er ikke juridisk rådgivning, og ingen jurist har kontrollert den. Les hver setning, fyll inn delene i [[klammer]], og slett denne merknaden når du har gjort det.",
    "notice.language": "Denne teksten er på norsk bokmål fordi den ikke finnes på butikkens språk: la en person oversette og gjennomgå den før bruk.",
    "ph.add": "Legg til",
    "ph.check": "Kontroller",
    "label.email": "e-postadresse for kontakt",
    "label.assessor": "hvem som vurderte nettstedet",
    "label.siteAddress": "nettstedets adresse",
    "label.storeName": "butikkens navn",
    "label.annex": "opplysningene EUs tilgjengelighetsdirektiv krever i en tjenesteleverandørs erklæring (vedlegg V)",
    "label.date": "dato",
    "label.microenterprise": "at virksomheten oppfyller vilkårene for en svært liten bedrift, og hvordan unntaket er formulert i landet ditt",
    "title": "Tilgjengelighetserklæring",
    "slug": "tilgjengelighetserklaering",
    "h.status": "Hvor tilgjengelig dette nettstedet er",
    "a11y.status.not_assessed": "{store} har ikke vurdert dette nettstedet mot kravene til universell utforming. Vi har som mål å bygge det etter Web Content Accessibility Guidelines (WCAG) 2.2, nivå AA, men vi har ikke kontrollert at det oppfyller dem, og sier derfor ikke at det gjør det.",
    "a11y.status.partial": "Dette nettstedet oppfyller delvis Web Content Accessibility Guidelines (WCAG) 2.2, nivå AA. Noen deler oppfyller dem ikke ennå, slik det står nedenfor.",
    "a11y.status.full": "Dette nettstedet oppfyller Web Content Accessibility Guidelines (WCAG) 2.2, nivå AA, slik det er vurdert nedenfor.",
    "a11y.status.note": "En automatisk kontroll finner bare noen av problemene som kan gjøre et nettsted vanskelig å bruke. Denne erklæringen er bare så god som vurderingen bak den.",
    "h.standard": "Standarden vi bygger etter",
    "a11y.standard.1": "Vi bygger etter WCAG 2.2 nivå AA. Den harmoniserte europeiske standarden for tilgjengelighet i informasjons- og kommunikasjonsteknologi er EN 301 549, som viser til WCAG.",
    "h.assessment": "Hvordan dette er vurdert",
    "a11y.assessment.none": "Det er ikke gjort noen uavhengig vurdering. Kontrollene vi selv kjører, er oppført under kjente problemer.",
    "a11y.assessment.by": "Vurdert av {by} den {on}.",
    "a11y.assessment.report": "Rapporten finnes på {url}.",
    "a11y.assessment.note": "Merknader til vurderingen: {note}",
    "h.scope": "Hva dette omfatter",
    "a11y.scope.1": "Denne erklæringen omfatter butikkens nettsted på {addresses}.",
    "a11y.scope.2": "Nettstedet finnes på: {languages}.",
    "h.known_issues": "Kjente problemer",
    "a11y.issue.theme": "Fargekombinasjoner i butikkens design under anbefalt kontrast på 4,5 til 1, så noe tekst kan være vanskelig å lese: {n}.",
    "a11y.issue.alt": "Bilder i butikkens mediebibliotek uten alternativ tekst: {missing} av {total}.",
    "a11y.issue.pages": "Publiserte sider med problemer som sidekontrollen markerer som blokkerende, for eksempel bilder uten alternativ tekst eller tomme lenker: {n}.",
    "a11y.issue.own": "{text}",
    "a11y.issues.none": "Vi kjenner ikke til problemer utover delene fra andre leverandører som er beskrevet nedenfor. Det betyr ikke at det ikke finnes noen.",
    "h.third_party": "Deler fra andre leverandører",
    "a11y.third.1": "Betalingen skjer i et skjema fra Stripe, som vi ikke bygger selv. Vi har ikke vurdert tilgjengeligheten av det selv.",
    "h.microenterprise": "Unntak for svært små bedrifter",
    "a11y.micro.1": "Virksomheten har opplyst at den er en svært liten bedrift, med færre enn 10 ansatte og en omsetning eller balanse på høyst 2 millioner euro. Svært små bedrifter som yter tjenester, er unntatt fra kravene til tjenester i EUs tilgjengelighetsdirektiv (direktiv (EU) 2019/882, artikkel 4 nr. 5). {check}",
    "h.feedback": "Si fra om et problem",
    "a11y.feedback.1": "Hvis du finner noe på dette nettstedet som du ikke kan bruke, skriv til oss på {email}. Oppgi adressen til siden og hva som gikk galt, så svarer vi.",
    "a11y.annex": "{check}",
    "h.enforcement": "Hvor du kan klage",
    "a11y.enforcement.1": "Hvis du ikke er fornøyd med svaret vårt, kan du henvende deg til myndigheten som fører tilsyn med tilgjengelighet:",
    "a11y.enforcement.verified": "{country}: {body}.",
    "a11y.enforcement.unverified": "{country}: kanskje {body}. Dette er ikke kontrollert: sjekk med myndigheten.",
    "a11y.enforcement.other": "{country}: den nasjonale markedstilsynsmyndigheten for tilgjengelighet. Europakommisjonen har en liste over dem. Dette er ikke kontrollert: sjekk med myndigheten.",
    "a11y.note.NO": "Det er ikke bekreftet om og hvordan Norge har tatt inn EUs tilgjengelighetsdirektiv. Reglene som gjelder deg i Norge: sjekk med Digdir.",
    "h.prepared": "Om denne erklæringen",
    "a11y.prepared.1": "Denne erklæringen ble utarbeidet {prepared}.",
    "a11y.prepared.2": "Den ble sist gjennomgått {reviewed}.",
  },
};

const SV: A11yText = {
  locale: "sv-SE",
  m: {
    notice:
      "UTKAST: måste granskas juridiskt före användning. Kaizen Store har gjort den här texten av butikens uppgifter och dina svar som en utgångspunkt. Den är inte juridisk rådgivning och ingen jurist har kontrollerat den. Läs varje mening, fyll i delarna inom [[hakparenteser]] och ta bort den här anteckningen när du har gjort det.",
    "notice.language": "Den här texten är på svenska eftersom den inte finns på butikens språk: låt en person översätta och granska den före användning.",
    "ph.add": "Lägg till",
    "ph.check": "Kontrollera",
    "label.email": "e-postadress för kontakt",
    "label.assessor": "vem som bedömde webbplatsen",
    "label.siteAddress": "webbplatsens adress",
    "label.storeName": "butikens namn",
    "label.annex": "de uppgifter som EU:s tillgänglighetsdirektiv kräver i en tjänsteleverantörs redogörelse (bilaga V)",
    "label.date": "datum",
    "label.microenterprise": "att verksamheten uppfyller villkoren för ett mikroföretag, och hur undantaget är formulerat i ditt land",
    "title": "Tillgänglighetsredogörelse",
    "slug": "tillganglighetsredogorelse",
    "h.status": "Hur tillgänglig den här webbplatsen är",
    "a11y.status.not_assessed": "{store} har inte bedömt den här webbplatsen mot tillgänglighetskraven. Vi strävar efter att bygga den enligt Web Content Accessibility Guidelines (WCAG) 2.2, nivå AA, men vi har inte kontrollerat att den uppfyller dem, och säger därför inte att den gör det.",
    "a11y.status.partial": "Den här webbplatsen uppfyller delvis Web Content Accessibility Guidelines (WCAG) 2.2, nivå AA. Vissa delar uppfyller dem inte ännu, som det står nedan.",
    "a11y.status.full": "Den här webbplatsen uppfyller Web Content Accessibility Guidelines (WCAG) 2.2, nivå AA, som det bedömts nedan.",
    "a11y.status.note": "En automatisk kontroll hittar bara en del av de problem som kan göra en webbplats svår att använda. Den här redogörelsen är bara så bra som bedömningen bakom den.",
    "h.standard": "Standarden vi bygger efter",
    "a11y.standard.1": "Vi bygger efter WCAG 2.2 nivå AA. Den harmoniserade europeiska standarden för tillgänglighet i informations- och kommunikationsteknik är EN 301 549, som hänvisar till WCAG.",
    "h.assessment": "Hur detta har bedömts",
    "a11y.assessment.none": "Ingen oberoende bedömning har gjorts. De kontroller vi själva kör finns uppräknade under kända brister.",
    "a11y.assessment.by": "Bedömd av {by} den {on}.",
    "a11y.assessment.report": "Rapporten finns på {url}.",
    "a11y.assessment.note": "Anteckningar om bedömningen: {note}",
    "h.scope": "Vad detta omfattar",
    "a11y.scope.1": "Den här redogörelsen omfattar butikens webbplats på {addresses}.",
    "a11y.scope.2": "Webbplatsen finns på: {languages}.",
    "h.known_issues": "Kända brister",
    "a11y.issue.theme": "Färgkombinationer i butikens design under den rekommenderade kontrasten på 4,5 till 1, så en del text kan vara svår att läsa: {n}.",
    "a11y.issue.alt": "Bilder i butikens mediebibliotek utan alternativtext: {missing} av {total}.",
    "a11y.issue.pages": "Publicerade sidor med problem som sidkontrollen markerar som blockerande, till exempel bilder utan alternativtext eller tomma länkar: {n}.",
    "a11y.issue.own": "{text}",
    "a11y.issues.none": "Vi känner inte till några brister utöver de delar från andra leverantörer som beskrivs nedan. Det betyder inte att det inte finns några.",
    "h.third_party": "Delar från andra leverantörer",
    "a11y.third.1": "Betalningen sker i ett formulär från Stripe, som vi inte bygger själva. Vi har inte själva bedömt dess tillgänglighet.",
    "h.microenterprise": "Undantag för mikroföretag",
    "a11y.micro.1": "Verksamheten har uppgett att den är ett mikroföretag, med färre än 10 anställda och en omsättning eller balansomslutning på högst 2 miljoner euro. Mikroföretag som tillhandahåller tjänster är undantagna från tillgänglighetskraven för tjänster i EU:s tillgänglighetsdirektiv (direktiv (EU) 2019/882, artikel 4.5). {check}",
    "h.feedback": "Berätta om ett problem",
    "a11y.feedback.1": "Om du hittar något på den här webbplatsen som du inte kan använda, skriv till oss på {email}. Ange sidans adress och vad som gick fel, så svarar vi.",
    "a11y.annex": "{check}",
    "h.enforcement": "Var du kan klaga",
    "a11y.enforcement.1": "Om du inte är nöjd med vårt svar kan du vända dig till den myndighet som utövar tillsyn över tillgänglighet:",
    "a11y.enforcement.verified": "{country}: {body}.",
    "a11y.enforcement.unverified": "{country}: möjligen {body}. Detta är inte kontrollerat: hör med myndigheten.",
    "a11y.enforcement.other": "{country}: den nationella marknadskontrollmyndigheten för tillgänglighet. Europeiska kommissionen för en förteckning över dem. Detta är inte kontrollerat: hör med myndigheten.",
    "a11y.note.NO": "Det är inte bekräftat om och hur Norge har tagit in EU:s tillgänglighetsdirektiv. Reglerna som gäller dig i Norge: hör med Digdir.",
    "h.prepared": "Om den här redogörelsen",
    "a11y.prepared.1": "Den här redogörelsen upprättades {prepared}.",
    "a11y.prepared.2": "Den granskades senast {reviewed}.",
  },
};

const DA: A11yText = {
  locale: "da-DK",
  m: {
    notice:
      "UDKAST: skal gennemgås juridisk før brug. Kaizen Store har lavet denne tekst af butikkens oplysninger og dine svar som et udgangspunkt. Den er ikke juridisk rådgivning, og ingen jurist har kontrolleret den. Læs hver sætning, udfyld delene i [[klammer]], og slet denne note, når du har gjort det.",
    "notice.language": "Denne tekst er på dansk, fordi den ikke findes på butikkens sprog: lad en person oversætte og gennemgå den før brug.",
    "ph.add": "Tilføj",
    "ph.check": "Kontrollér",
    "label.email": "e-mailadresse til kontakt",
    "label.assessor": "hvem der vurderede websitet",
    "label.siteAddress": "websitets adresse",
    "label.storeName": "butikkens navn",
    "label.annex": "de oplysninger, EU's tilgængelighedsdirektiv kræver i en tjenesteudbyders erklæring (bilag V)",
    "label.date": "dato",
    "label.microenterprise": "at virksomheden opfylder betingelserne for en mikrovirksomhed, og hvordan undtagelsen er formuleret i dit land",
    "title": "Tilgængelighedserklæring",
    "slug": "tilgaengelighedserklaering",
    "h.status": "Hvor tilgængeligt dette website er",
    "a11y.status.not_assessed": "{store} har ikke vurderet dette website i forhold til tilgængelighedskravene. Vi bestræber os på at bygge det efter Web Content Accessibility Guidelines (WCAG) 2.2, niveau AA, men vi har ikke kontrolleret, at det opfylder dem, og siger derfor ikke, at det gør det.",
    "a11y.status.partial": "Dette website opfylder delvist Web Content Accessibility Guidelines (WCAG) 2.2, niveau AA. Nogle dele opfylder dem ikke endnu, som det fremgår nedenfor.",
    "a11y.status.full": "Dette website opfylder Web Content Accessibility Guidelines (WCAG) 2.2, niveau AA, som det er vurderet nedenfor.",
    "a11y.status.note": "En automatisk kontrol finder kun nogle af de problemer, der kan gøre et website svært at bruge. Denne erklæring er kun så god som den vurdering, der ligger bag.",
    "h.standard": "Den standard vi bygger efter",
    "a11y.standard.1": "Vi bygger efter WCAG 2.2 niveau AA. Den harmoniserede europæiske standard for tilgængelighed i informations- og kommunikationsteknologi er EN 301 549, som henviser til WCAG.",
    "h.assessment": "Hvordan dette er vurderet",
    "a11y.assessment.none": "Der er ikke foretaget nogen uafhængig vurdering. De kontroller, vi selv kører, er opført under kendte problemer.",
    "a11y.assessment.by": "Vurderet af {by} den {on}.",
    "a11y.assessment.report": "Rapporten findes på {url}.",
    "a11y.assessment.note": "Noter til vurderingen: {note}",
    "h.scope": "Hvad dette omfatter",
    "a11y.scope.1": "Denne erklæring omfatter butikkens website på {addresses}.",
    "a11y.scope.2": "Websitet findes på: {languages}.",
    "h.known_issues": "Kendte problemer",
    "a11y.issue.theme": "Farvekombinationer i butikkens design under den anbefalede kontrast på 4,5 til 1, så noget tekst kan være svær at læse: {n}.",
    "a11y.issue.alt": "Billeder i butikkens mediebibliotek uden alternativ tekst: {missing} af {total}.",
    "a11y.issue.pages": "Offentliggjorte sider med problemer, som sidekontrollen markerer som blokerende, for eksempel billeder uden alternativ tekst eller tomme links: {n}.",
    "a11y.issue.own": "{text}",
    "a11y.issues.none": "Vi kender ikke til problemer ud over de dele fra andre leverandører, der er beskrevet nedenfor. Det betyder ikke, at der ikke er nogen.",
    "h.third_party": "Dele fra andre leverandører",
    "a11y.third.1": "Betalingen sker i en formular fra Stripe, som vi ikke selv bygger. Vi har ikke selv vurderet dens tilgængelighed.",
    "h.microenterprise": "Undtagelse for mikrovirksomheder",
    "a11y.micro.1": "Virksomheden har oplyst, at den er en mikrovirksomhed, med færre end 10 ansatte og en omsætning eller balance på højst 2 millioner euro. Mikrovirksomheder, der leverer tjenesteydelser, er undtaget fra tilgængelighedskravene til tjenesteydelser i EU's tilgængelighedsdirektiv (direktiv (EU) 2019/882, artikel 4, stk. 5). {check}",
    "h.feedback": "Fortæl os om et problem",
    "a11y.feedback.1": "Hvis du finder noget på dette website, som du ikke kan bruge, så skriv til os på {email}. Oplys sidens adresse og hvad der gik galt, så svarer vi.",
    "a11y.annex": "{check}",
    "h.enforcement": "Hvor du kan klage",
    "a11y.enforcement.1": "Hvis du ikke er tilfreds med vores svar, kan du henvende dig til den myndighed, der fører tilsyn med tilgængelighed:",
    "a11y.enforcement.verified": "{country}: {body}.",
    "a11y.enforcement.unverified": "{country}: muligvis {body}. Dette er ikke kontrolleret: tjek med myndigheden.",
    "a11y.enforcement.other": "{country}: den nationale markedsovervågningsmyndighed for tilgængelighed. Europa-Kommissionen fører en liste over dem. Dette er ikke kontrolleret: tjek med myndigheden.",
    "a11y.note.NO": "Det er ikke bekræftet, om og hvordan Norge har indarbejdet EU's tilgængelighedsdirektiv. De regler, der gælder for dig i Norge: tjek med Digdir.",
    "h.prepared": "Om denne erklæring",
    "a11y.prepared.1": "Denne erklæring blev udarbejdet {prepared}.",
    "a11y.prepared.2": "Den blev senest gennemgået {reviewed}.",
  },
};

export const A11Y_TEXTS: Record<StarterLanguage, A11yText> = { nb: NB, sv: SV, da: DA, en: EN };
