/**
 * The words in Kaizen's emails to shoppers (D26), by language. English is
 * the fallback, as for the storefront.
 */
const text = {
  nb: {
    orderSubject: (store: string, number: string) => `Ordrebekreftelse ${number} fra ${store}`,
    orderHeading: "Takk for bestillingen!",
    orderIntro: (number: string) => `Vi har mottatt betalingen for ordre ${number}.`,
    renewalSubject: (store: string, number: string) => `Abonnementet ditt er fornyet: ordre ${number} fra ${store}`,
    renewalIntro: (number: string) => `Abonnementet ditt er fornyet, og ordre ${number} er betalt.`,
    subtotal: "Sum varer",
    shipping: "Frakt",
    total: "Totalt",
    vat: "herav mva.",
    deliverTo: "Leveres til",
    seeOrder: "Se bestillingen",
    downloadsReady: "Filene dine er klare til nedlasting fra bestillingssiden.",
    subscription: (every: string, amount: string) =>
      `Abonnement: fornyes ${every.toLowerCase()} for ${amount} til du sier opp.`,
    manageSubscription: "Se eller endre abonnementet",
    account: "Min konto",
    questions: (email: string) => `Spørsmål? Svar på denne e-posten eller skriv til ${email}.`,
    shippedSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er sendt`,
    shippedHeading: "Pakken er på vei!",
    shippedIntro: (number: string) => `Ordre ${number} er sendt.`,
    tracking: (carrier: string, number: string) => `Sporing: ${carrier} ${number}`.trim(),
    trackParcel: "Spor pakken",
    refundSubject: (store: string, number: string) => `Refusjon for ordre ${number} fra ${store}`,
    refundHeading: "Vi har refundert deg",
    refundIntro: (amount: string, number: string) =>
      `Vi har refundert ${amount} for ordre ${number}. Det tar vanligvis 5–10 virkedager før beløpet er tilbake på kontoen din.`,
    cancelledSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er kansellert`,
    cancelledHeading: "Bestillingen er kansellert",
    cancelledIntro: (number: string, amount: string) =>
      `Ordre ${number} er kansellert, og ${amount} er refundert.`,
    codeSubject: (store: string) => `Innloggingskode for ${store}`,
    codeHeading: "Innloggingskoden din",
    codeIntro: "Skriv inn koden for å logge inn. Den virker i 10 minutter.",
    codeIgnore: "Ba du ikke om denne koden? Da kan du se bort fra e-posten.",
    reminderSubject: (store: string, date: string) => `Abonnementet ditt hos ${store} fornyes ${date}`,
    reminderHeading: "Påminnelse om fornyelse",
    reminderIntro: (date: string, amount: string) =>
      `Abonnementet ditt fornyes ${date}, og du blir belastet ${amount}.`,
    reminderChange: "Du kan hoppe over, sette på pause, endre eller si opp før da.",
    trialSubject: (store: string, date: string) => `Prøveperioden din hos ${store} slutter ${date}`,
    trialHeading: "Prøveperioden nærmer seg slutten",
    trialIntro: (date: string, amount: string) =>
      `Prøveperioden slutter ${date}. Deretter fortsetter abonnementet, og du blir belastet ${amount}.`,
    changedSubject: (store: string) => `Abonnementet ditt hos ${store} er endret`,
    changedHeading: "Abonnementet er endret",
    changes: {
      cancel: (date: string) => `Abonnementet avsluttes ${date}. Du blir ikke belastet mer.`,
      resume: () => "Abonnementet fortsetter som før.",
      cancel_now: () => "Abonnementet er avsluttet.",
      pause: (date: string) => `Abonnementet er satt på pause til ${date}.`,
      unpause: () => "Pausen er avsluttet, og abonnementet fortsetter.",
      skip: (date: string) => `Neste levering er hoppet over. Neste belastning blir ${date}.`,
      change: () => "Innholdet i abonnementet er endret fra neste fornyelse.",
    },
  },
  sv: {
    orderSubject: (store: string, number: string) => `Orderbekräftelse ${number} från ${store}`,
    orderHeading: "Tack för din beställning!",
    orderIntro: (number: string) => `Vi har tagit emot betalningen för order ${number}.`,
    renewalSubject: (store: string, number: string) => `Din prenumeration har förnyats: order ${number} från ${store}`,
    renewalIntro: (number: string) => `Din prenumeration har förnyats och order ${number} är betald.`,
    subtotal: "Summa varor",
    shipping: "Frakt",
    total: "Totalt",
    vat: "varav moms",
    deliverTo: "Levereras till",
    seeOrder: "Se beställningen",
    downloadsReady: "Dina filer är redo att laddas ned från beställningssidan.",
    subscription: (every: string, amount: string) =>
      `Prenumeration: förnyas ${every.toLowerCase()} för ${amount} tills du säger upp den.`,
    manageSubscription: "Se eller ändra prenumerationen",
    account: "Mitt konto",
    questions: (email: string) => `Frågor? Svara på det här mejlet eller skriv till ${email}.`,
    shippedSubject: (store: string, number: string) => `Order ${number} från ${store} har skickats`,
    shippedHeading: "Paketet är på väg!",
    shippedIntro: (number: string) => `Order ${number} har skickats.`,
    tracking: (carrier: string, number: string) => `Spårning: ${carrier} ${number}`.trim(),
    trackParcel: "Spåra paketet",
    refundSubject: (store: string, number: string) => `Återbetalning för order ${number} från ${store}`,
    refundHeading: "Vi har återbetalat dig",
    refundIntro: (amount: string, number: string) =>
      `Vi har återbetalat ${amount} för order ${number}. Det tar oftast 5–10 bankdagar innan beloppet syns på ditt konto.`,
    cancelledSubject: (store: string, number: string) => `Order ${number} från ${store} har avbrutits`,
    cancelledHeading: "Beställningen har avbrutits",
    cancelledIntro: (number: string, amount: string) =>
      `Order ${number} har avbrutits och ${amount} har återbetalats.`,
    codeSubject: (store: string) => `Inloggningskod för ${store}`,
    codeHeading: "Din inloggningskod",
    codeIntro: "Ange koden för att logga in. Den gäller i 10 minuter.",
    codeIgnore: "Bad du inte om koden? Då kan du bortse från mejlet.",
    reminderSubject: (store: string, date: string) => `Din prenumeration hos ${store} förnyas ${date}`,
    reminderHeading: "Påminnelse om förnyelse",
    reminderIntro: (date: string, amount: string) =>
      `Din prenumeration förnyas ${date} och du debiteras ${amount}.`,
    reminderChange: "Du kan hoppa över, pausa, ändra eller säga upp före dess.",
    trialSubject: (store: string, date: string) => `Din provperiod hos ${store} slutar ${date}`,
    trialHeading: "Provperioden närmar sig sitt slut",
    trialIntro: (date: string, amount: string) =>
      `Provperioden slutar ${date}. Därefter fortsätter prenumerationen och du debiteras ${amount}.`,
    changedSubject: (store: string) => `Din prenumeration hos ${store} har ändrats`,
    changedHeading: "Prenumerationen har ändrats",
    changes: {
      cancel: (date: string) => `Prenumerationen avslutas ${date}. Du debiteras inte mer.`,
      resume: () => "Prenumerationen fortsätter som tidigare.",
      cancel_now: () => "Prenumerationen är avslutad.",
      pause: (date: string) => `Prenumerationen är pausad till ${date}.`,
      unpause: () => "Pausen är avslutad och prenumerationen fortsätter.",
      skip: (date: string) => `Nästa leverans hoppas över. Nästa debitering blir ${date}.`,
      change: () => "Innehållet i prenumerationen ändras från nästa förnyelse.",
    },
  },
  da: {
    orderSubject: (store: string, number: string) => `Ordrebekræftelse ${number} fra ${store}`,
    orderHeading: "Tak for din bestilling!",
    orderIntro: (number: string) => `Vi har modtaget betalingen for ordre ${number}.`,
    renewalSubject: (store: string, number: string) => `Dit abonnement er fornyet: ordre ${number} fra ${store}`,
    renewalIntro: (number: string) => `Dit abonnement er fornyet, og ordre ${number} er betalt.`,
    subtotal: "Varer i alt",
    shipping: "Fragt",
    total: "I alt",
    vat: "heraf moms",
    deliverTo: "Leveres til",
    seeOrder: "Se bestillingen",
    downloadsReady: "Dine filer er klar til download fra bestillingssiden.",
    subscription: (every: string, amount: string) =>
      `Abonnement: fornyes ${every.toLowerCase()} for ${amount}, indtil du opsiger det.`,
    manageSubscription: "Se eller ændr abonnementet",
    account: "Min konto",
    questions: (email: string) => `Spørgsmål? Svar på denne mail, eller skriv til ${email}.`,
    shippedSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er sendt`,
    shippedHeading: "Pakken er på vej!",
    shippedIntro: (number: string) => `Ordre ${number} er sendt.`,
    tracking: (carrier: string, number: string) => `Sporing: ${carrier} ${number}`.trim(),
    trackParcel: "Spor pakken",
    refundSubject: (store: string, number: string) => `Refundering for ordre ${number} fra ${store}`,
    refundHeading: "Vi har refunderet dig",
    refundIntro: (amount: string, number: string) =>
      `Vi har refunderet ${amount} for ordre ${number}. Der går normalt 5–10 bankdage, før beløbet er tilbage på din konto.`,
    cancelledSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er annulleret`,
    cancelledHeading: "Bestillingen er annulleret",
    cancelledIntro: (number: string, amount: string) =>
      `Ordre ${number} er annulleret, og ${amount} er refunderet.`,
    codeSubject: (store: string) => `Loginkode til ${store}`,
    codeHeading: "Din loginkode",
    codeIntro: "Indtast koden for at logge ind. Den virker i 10 minutter.",
    codeIgnore: "Bad du ikke om koden? Så kan du se bort fra denne mail.",
    reminderSubject: (store: string, date: string) => `Dit abonnement hos ${store} fornyes ${date}`,
    reminderHeading: "Påmindelse om fornyelse",
    reminderIntro: (date: string, amount: string) =>
      `Dit abonnement fornyes ${date}, og du bliver opkrævet ${amount}.`,
    reminderChange: "Du kan springe over, sætte på pause, ændre eller opsige inden da.",
    trialSubject: (store: string, date: string) => `Din prøveperiode hos ${store} slutter ${date}`,
    trialHeading: "Prøveperioden nærmer sig sin afslutning",
    trialIntro: (date: string, amount: string) =>
      `Prøveperioden slutter ${date}. Derefter fortsætter abonnementet, og du bliver opkrævet ${amount}.`,
    changedSubject: (store: string) => `Dit abonnement hos ${store} er ændret`,
    changedHeading: "Abonnementet er ændret",
    changes: {
      cancel: (date: string) => `Abonnementet slutter ${date}. Du bliver ikke opkrævet mere.`,
      resume: () => "Abonnementet fortsætter som før.",
      cancel_now: () => "Abonnementet er afsluttet.",
      pause: (date: string) => `Abonnementet er sat på pause til ${date}.`,
      unpause: () => "Pausen er slut, og abonnementet fortsætter.",
      skip: (date: string) => `Næste levering springes over. Næste opkrævning bliver ${date}.`,
      change: () => "Indholdet i abonnementet ændres fra næste fornyelse.",
    },
  },
  en: {
    orderSubject: (store: string, number: string) => `Order confirmation ${number} from ${store}`,
    orderHeading: "Thank you for your order!",
    orderIntro: (number: string) => `We have received the payment for order ${number}.`,
    renewalSubject: (store: string, number: string) => `Your subscription has renewed: order ${number} from ${store}`,
    renewalIntro: (number: string) => `Your subscription has renewed, and order ${number} is paid.`,
    subtotal: "Subtotal",
    shipping: "Shipping",
    total: "Total",
    vat: "incl. VAT",
    deliverTo: "Delivered to",
    seeOrder: "See the order",
    downloadsReady: "Your files are ready to download from the order page.",
    subscription: (every: string, amount: string) =>
      `Subscription: renews ${every.toLowerCase()} at ${amount} until you cancel.`,
    manageSubscription: "See or change the subscription",
    account: "My account",
    questions: (email: string) => `Questions? Reply to this email or write to ${email}.`,
    shippedSubject: (store: string, number: string) => `Order ${number} from ${store} is on its way`,
    shippedHeading: "Your parcel is on its way!",
    shippedIntro: (number: string) => `Order ${number} has been sent.`,
    tracking: (carrier: string, number: string) => `Tracking: ${carrier} ${number}`.trim(),
    trackParcel: "Track the parcel",
    refundSubject: (store: string, number: string) => `Refund for order ${number} from ${store}`,
    refundHeading: "We have refunded you",
    refundIntro: (amount: string, number: string) =>
      `We have refunded ${amount} for order ${number}. It usually takes 5–10 working days to reach your account.`,
    cancelledSubject: (store: string, number: string) => `Order ${number} from ${store} is cancelled`,
    cancelledHeading: "Your order is cancelled",
    cancelledIntro: (number: string, amount: string) =>
      `Order ${number} is cancelled and ${amount} has been refunded.`,
    codeSubject: (store: string) => `Sign-in code for ${store}`,
    codeHeading: "Your sign-in code",
    codeIntro: "Enter the code to sign in. It works for 10 minutes.",
    codeIgnore: "Did not ask for this code? You can ignore this email.",
    reminderSubject: (store: string, date: string) => `Your subscription at ${store} renews on ${date}`,
    reminderHeading: "Renewal reminder",
    reminderIntro: (date: string, amount: string) =>
      `Your subscription renews on ${date}, and you will be charged ${amount}.`,
    reminderChange: "You can skip, pause, change or cancel before then.",
    trialSubject: (store: string, date: string) => `Your trial at ${store} ends on ${date}`,
    trialHeading: "Your trial is ending soon",
    trialIntro: (date: string, amount: string) =>
      `Your trial ends on ${date}. The subscription then continues, and you will be charged ${amount}.`,
    changedSubject: (store: string) => `Your subscription at ${store} has changed`,
    changedHeading: "Your subscription has changed",
    changes: {
      cancel: (date: string) => `The subscription ends on ${date}. You will not be charged again.`,
      resume: () => "The subscription continues as before.",
      cancel_now: () => "The subscription has ended.",
      pause: (date: string) => `The subscription is paused until ${date}.`,
      unpause: () => "The pause is over and the subscription continues.",
      skip: (date: string) => `The next delivery is skipped. The next charge is on ${date}.`,
      change: () => "What the subscription holds changes from the next renewal.",
    },
  },
};

export type EmailText = (typeof text)["en"];

export function emailText(lang: string): EmailText {
  return lang in text ? text[lang as keyof typeof text] : text.en;
}
