/**
 * The words in Kaizen's emails to shoppers (D26), by language. English is
 * the fallback, as for the storefront.
 */
const text = {
  nb: {
    deliveries: {
      startedSubject: (store: string) => `Abonnementsboksen din fra ${store} er klar`,
      startedHeading: "Abonnementsboksen din er klar",
      startedIntro: (day: string, cutoff: string) =>
        `Vi leverer listen din hver ${day}. Du kan endre den til ${cutoff} før hver levering; endringer etter det gjelder neste.`,
      startedCharge:
        "Vi trekker kortet ditt for hver levering når den er på vei, for det den inneholder til dagens priser. Endrer du ingenting, blir neste levering lik den forrige.",
      startedCancel: "Du kan hoppe over en levering, sette den på pause eller avslutte når du vil, fra siden for abonnementsboksen.",
      preparedSubject: (store: string, date: string) => `Leveringen din fra ${store} ${date}`,
      preparedHeading: "Neste levering",
      preparedIntro: (date: string) => `Leveringen din ${date} blir pakket nå.`,
      preparedCharge: (amount: string) => `Vi trekker ${amount} fra kortet ditt når den er på vei.`,
      leftOutHeading: "Ikke med denne gangen",
      leftOutLine: (title: string, wanted: number, got: number) => (got > 0 ? `${title}: ${got} av ${wanted}` : `${title}: utsolgt`),
      nothingIntro: (date: string) =>
        `Ingenting på listen din var å få til leveringen ${date}, så det blir ingen levering og ingen trekk denne gangen.`,
      manage: "Se eller endre abonnementsboksen",
      cardSubject: (store: string, number: string) => `Betal leveringen ${number} fra ${store}`,
      cardHeading: "Kortet ditt ble ikke trukket",
      cardIntro: (number: string, amount: string) =>
        `Vi fikk ikke trukket ${amount} for leveringen ${number}. Betal her; kortet du betaler med, brukes til de neste leveringene.`,
      payNow: "Betal leveringen",
    },
    orderSubject: (store: string, number: string) => `Ordrebekreftelse ${number} fra ${store}`,
    orderHeading: "Takk for bestillingen!",
    orderIntro: (number: string) => `Vi har mottatt betalingen for ordre ${number}.`,
    renewalSubject: (store: string, number: string) => `Abonnementet ditt er fornyet: ordre ${number} fra ${store}`,
    renewalIntro: (number: string) => `Abonnementet ditt er fornyet, og ordre ${number} er betalt.`,
    subtotal: "Sum varer",
    discount: "Rabatt",
    shipping: "Frakt",
    total: "Totalt",
    vat: "herav mva.",
    deliverTo: "Leveres til",
    seeOrder: "Se bestillingen",
    downloadsReady: "Filene dine er klare til nedlasting fra bestillingssiden.",
    subscription: (every: string, amount: string) =>
      `Abonnement: fornyes ${every.toLowerCase()} for ${amount} til du sier opp.`,
    manageSubscription: "Se eller endre abonnementet",
    account: "Min konto",
    questions: (email: string) => `Spørsmål? Svar på denne e-posten eller skriv til ${email}.`,
    shippedSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er sendt`,
    shippedHeading: "Pakken er på vei!",
    shippedIntro: (number: string) => `Ordre ${number} er sendt.`,
    tracking: (carrier: string, number: string) => `Sporing: ${carrier} ${number}`.trim(),
    trackParcel: "Spor pakken",
    refundSubject: (store: string, number: string) => `Refusjon for ordre ${number} fra ${store}`,
    refundHeading: "Vi har refundert deg",
    refundIntro: (amount: string, number: string) =>
      `Vi har refundert ${amount} for ordre ${number}. Det tar vanligvis 5–10 virkedager før beløpet er tilbake på kontoen din.`,
    cancelledSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er kansellert`,
    cancelledHeading: "Bestillingen er kansellert",
    cancelledIntro: (number: string, amount: string) =>
      `Ordre ${number} er kansellert, og ${amount} er refundert.`,
    cancelledUnpaidIntro: (number: string) => `Ordre ${number} er kansellert. Ingenting ble trukket.`,
    /** Appointments (D65). */
    bookingMovedSubject: (store: string, when: string) => `Ny tid hos ${store}: ${when}`,
    bookingMovedHeading: "Timen er flyttet",
    bookingMovedIntro: (when: string) => `Timen din er nå ${when}.`,
    bookingCancelledByYouSubject: (store: string, when: string) => `Du har avbestilt timen ${when} hos ${store}`,
    bookingCancelledByYouHeading: "Timen er avbestilt",
    bookingCancelledByYouIntro: (service: string, when: string, refund: string | null) =>
      `Du har avbestilt ${service} ${when}.${refund ? ` Vi betaler tilbake ${refund}; det tar vanligvis 5–10 virkedager.` : ""}`,
    appointmentsHeading: "Timen din",
    calendarNote: "Legg timen i kalenderen din med vedlegget.",
    bookingReminderSubject: (store: string, when: string) => `Påminnelse: timen din hos ${store} ${when}`,
    bookingReminderHeading: "Vi ses snart",
    bookingReminderIntro: (when: string) => `Dette er en påminnelse om timen din ${when}.`,
    bookingCancelledSubject: (store: string, when: string) => `Timen din hos ${store} ${when} er avlyst`,
    bookingCancelledHeading: "Timen er avlyst",
    bookingCancelledIntro: (service: string, when: string) =>
      `Vi har dessverre måttet avlyse ${service} ${when}. Svar på denne e-posten hvis du vil ha en ny tid eller har spørsmål om betalingen.`,
    codeSubject: (store: string) => `Innloggingskode for ${store}`,
    codeHeading: "Innloggingskoden din",
    codeIntro: "Skriv inn koden for å logge inn. Den virker i 10 minutter.",
    codeIgnore: "Ba du ikke om denne koden? Da kan du se bort fra e-posten.",
    resetSubject: (store: string) => `Nytt passord hos ${store}`,
    resetHeading: "Koden for nytt passord",
    resetIntro: "Skriv inn koden og velg et nytt passord. Den virker i 10 minutter.",
    welcomeSubject: (store: string) => `Velkommen til ${store}`,
    welcomeHeading: "Kontoen din er klar",
    welcomeIntro: (email: string) => `Du logger inn på Min konto med ${email} og passordet du valgte. Der ser du bestillinger og abonnementer, og kan endre opplysningene dine.`,
    welcomeButton: "Gå til Min konto",
    welcomeIgnore: "Opprettet du ikke denne kontoen? Svar på denne e-posten, så sletter butikken den.",
    company: {
      inviteSubject: (company: string, store: string) => `${company} inviterer deg til ${store}`,
      inviteHeading: (company: string) => `Du er invitert til ${company}`,
      inviteIntro: (inviter: string, company: string, store: string) =>
        `${inviter} har invitert deg til å bli med i kontoen til ${company} hos ${store}.`,
      inviteDiscount: (percent: string) => `Som ansatt får du ${percent} % rabatt på det du kjøper.`,
      inviteButton: "Godta invitasjonen",
      inviteExpires: (date: string) => `Invitasjonen kan godtas til ${date}.`,
      inviteIgnore: "Ventet du ikke denne? Ignorer e-posten, så skjer ingenting før du godtar.",
      joinedSubject: (store: string) => `Du er med hos ${store}`,
      joinedHeading: (company: string) => `Du er nå med i ${company}`,
      joinedNew: (email: string) => `Vi har opprettet en konto for ${email}. Bruk knappen under for å logge inn.`,
      joinedExisting: (email: string) => `Kontoen din (${email}) er nå knyttet til firmaet. Bruk knappen under for å logge inn.`,
      joinedDiscount: (percent: string) => `Du får ${percent} % rabatt på det du kjøper når du er logget inn.`,
      joinedButton: "Logg inn",
      joinedLinkNote: "Lenken virker én gang og i sju dager. Etterpå kan du logge inn med en kode fra Min konto.",
      endedSubject: (company: string) => `Du er ikke lenger med i ${company}`,
      endedHeading: "Firmarabatten din er avsluttet",
      endedIntro: (company: string, store: string) =>
        `Du er ikke lenger knyttet til ${company} hos ${store}, så firmarabatten gjelder ikke lenger. Kontoen din og bestillingene dine er som før.`,
    },
    reminderSubject: (store: string, date: string) => `Abonnementet ditt hos ${store} fornyes ${date}`,
    reminderHeading: "Påminnelse om fornyelse",
    reminderIntro: (date: string, amount: string) =>
      `Abonnementet ditt fornyes ${date}, og du blir belastet ${amount}.`,
    reminderChange: "Du kan hoppe over, sette på pause, endre eller si opp før da.",
    trialSubject: (store: string, date: string) => `Prøveperioden din hos ${store} slutter ${date}`,
    trialHeading: "Prøveperioden nærmer seg slutten",
    trialIntro: (date: string, amount: string) =>
      `Prøveperioden slutter ${date}. Deretter fortsetter abonnementet, og du blir belastet ${amount}.`,
    changedSubject: (store: string) => `Abonnementet ditt hos ${store} er endret`,
    changedHeading: "Abonnementet er endret",
    changes: {
      cancel: (date: string) => `Abonnementet avsluttes ${date}. Du blir ikke belastet mer.`,
      resume: () => "Abonnementet fortsetter som før.",
      cancel_now: () => "Abonnementet er avsluttet.",
      pause: (date: string) => `Abonnementet er satt på pause til ${date}.`,
      unpause: () => "Pausen er avsluttet, og abonnementet fortsetter.",
      skip: (date: string) => `Neste levering er hoppet over. Neste belastning blir ${date}.`,
      change: () => "Innholdet i abonnementet er endret fra neste fornyelse.",
    },
  },
  sv: {
    deliveries: {
      startedSubject: (store: string) => `Din prenumerationsbox från ${store} är klar`,
      startedHeading: "Din prenumerationsbox är klar",
      startedIntro: (day: string, cutoff: string) =>
        `Vi levererar din lista varje ${day}. Du kan ändra den till ${cutoff} före varje leverans; ändringar efter det gäller nästa.`,
      startedCharge:
        "Vi drar pengarna från ditt kort för varje leverans när den är på väg, för det den innehåller till dagens priser. Ändrar du inget blir nästa leverans likadan som den förra.",
      startedCancel: "Du kan hoppa över en leverans, pausa eller avsluta när du vill, på sidan för din prenumerationsbox.",
      preparedSubject: (store: string, date: string) => `Din leverans från ${store} ${date}`,
      preparedHeading: "Nästa leverans",
      preparedIntro: (date: string) => `Din leverans ${date} packas nu.`,
      preparedCharge: (amount: string) => `Vi drar ${amount} från ditt kort när den är på väg.`,
      leftOutHeading: "Inte med den här gången",
      leftOutLine: (title: string, wanted: number, got: number) => (got > 0 ? `${title}: ${got} av ${wanted}` : `${title}: slutsåld`),
      nothingIntro: (date: string) =>
        `Inget på din lista gick att få till leveransen ${date}, så det blir ingen leverans och inget köp den här gången.`,
      manage: "Se eller ändra din prenumerationsbox",
      cardSubject: (store: string, number: string) => `Betala leveransen ${number} från ${store}`,
      cardHeading: "Ditt kort drogs inte",
      cardIntro: (number: string, amount: string) =>
        `Vi kunde inte dra ${amount} för leveransen ${number}. Betala här; kortet du betalar med används för kommande leveranser.`,
      payNow: "Betala leveransen",
    },
    orderSubject: (store: string, number: string) => `Orderbekräftelse ${number} från ${store}`,
    orderHeading: "Tack för din beställning!",
    orderIntro: (number: string) => `Vi har tagit emot betalningen för order ${number}.`,
    renewalSubject: (store: string, number: string) => `Din prenumeration har förnyats: order ${number} från ${store}`,
    renewalIntro: (number: string) => `Din prenumeration har förnyats och order ${number} är betald.`,
    subtotal: "Summa varor",
    discount: "Rabatt",
    shipping: "Frakt",
    total: "Totalt",
    vat: "varav moms",
    deliverTo: "Levereras till",
    seeOrder: "Se beställningen",
    downloadsReady: "Dina filer är redo att laddas ned från beställningssidan.",
    subscription: (every: string, amount: string) =>
      `Prenumeration: förnyas ${every.toLowerCase()} för ${amount} tills du säger upp den.`,
    manageSubscription: "Se eller ändra prenumerationen",
    account: "Mitt konto",
    questions: (email: string) => `Frågor? Svara på det här mejlet eller skriv till ${email}.`,
    shippedSubject: (store: string, number: string) => `Order ${number} från ${store} har skickats`,
    shippedHeading: "Paketet är på väg!",
    shippedIntro: (number: string) => `Order ${number} har skickats.`,
    tracking: (carrier: string, number: string) => `Spårning: ${carrier} ${number}`.trim(),
    trackParcel: "Spåra paketet",
    refundSubject: (store: string, number: string) => `Återbetalning för order ${number} från ${store}`,
    refundHeading: "Vi har återbetalat dig",
    refundIntro: (amount: string, number: string) =>
      `Vi har återbetalat ${amount} för order ${number}. Det tar oftast 5–10 bankdagar innan beloppet syns på ditt konto.`,
    cancelledSubject: (store: string, number: string) => `Order ${number} från ${store} har avbrutits`,
    cancelledHeading: "Beställningen har avbrutits",
    cancelledIntro: (number: string, amount: string) =>
      `Order ${number} har avbrutits och ${amount} har återbetalats.`,
    cancelledUnpaidIntro: (number: string) => `Order ${number} är avbruten. Inget har dragits.`,
    /** Appointments (D65). */
    bookingMovedSubject: (store: string, when: string) => `Ny tid hos ${store}: ${when}`,
    bookingMovedHeading: "Tiden är flyttad",
    bookingMovedIntro: (when: string) => `Din tid är nu ${when}.`,
    bookingCancelledByYouSubject: (store: string, when: string) => `Du har avbokat tiden ${when} hos ${store}`,
    bookingCancelledByYouHeading: "Tiden är avbokad",
    bookingCancelledByYouIntro: (service: string, when: string, refund: string | null) =>
      `Du har avbokat ${service} ${when}.${refund ? ` Vi betalar tillbaka ${refund}; det tar oftast 5–10 bankdagar.` : ""}`,
    appointmentsHeading: "Din tid",
    calendarNote: "Lägg in tiden i din kalender med bilagan.",
    bookingReminderSubject: (store: string, when: string) => `Påminnelse: din tid hos ${store} ${when}`,
    bookingReminderHeading: "Vi ses snart",
    bookingReminderIntro: (when: string) => `Det här är en påminnelse om din tid ${when}.`,
    bookingCancelledSubject: (store: string, when: string) => `Din tid hos ${store} ${when} är inställd`,
    bookingCancelledHeading: "Tiden är inställd",
    bookingCancelledIntro: (service: string, when: string) =>
      `Vi har tyvärr fått ställa in ${service} ${when}. Svara på det här mejlet om du vill boka en ny tid eller har frågor om betalningen.`,
    codeSubject: (store: string) => `Inloggningskod för ${store}`,
    codeHeading: "Din inloggningskod",
    codeIntro: "Ange koden för att logga in. Den gäller i 10 minuter.",
    codeIgnore: "Bad du inte om koden? Då kan du bortse från mejlet.",
    resetSubject: (store: string) => `Nytt lösenord hos ${store}`,
    resetHeading: "Koden för nytt lösenord",
    resetIntro: "Ange koden och välj ett nytt lösenord. Den gäller i 10 minuter.",
    welcomeSubject: (store: string) => `Välkommen till ${store}`,
    welcomeHeading: "Ditt konto är klart",
    welcomeIntro: (email: string) => `Du loggar in på Mitt konto med ${email} och lösenordet du valde. Där ser du beställningar och prenumerationer och kan ändra dina uppgifter.`,
    welcomeButton: "Till Mitt konto",
    welcomeIgnore: "Skapade du inte kontot? Svara på mejlet, så tar butiken bort det.",
    company: {
      inviteSubject: (company: string, store: string) => `${company} bjuder in dig till ${store}`,
      inviteHeading: (company: string) => `Du är inbjuden till ${company}`,
      inviteIntro: (inviter: string, company: string, store: string) =>
        `${inviter} har bjudit in dig att gå med i ${company}s konto hos ${store}.`,
      inviteDiscount: (percent: string) => `Som anställd får du ${percent} % rabatt på det du köper.`,
      inviteButton: "Acceptera inbjudan",
      inviteExpires: (date: string) => `Inbjudan kan accepteras till ${date}.`,
      inviteIgnore: "Väntade du dig inte detta? Ignorera mejlet, så händer inget förrän du accepterar.",
      joinedSubject: (store: string) => `Du är med hos ${store}`,
      joinedHeading: (company: string) => `Du är nu med i ${company}`,
      joinedNew: (email: string) => `Vi har skapat ett konto för ${email}. Använd knappen nedan för att logga in.`,
      joinedExisting: (email: string) => `Ditt konto (${email}) är nu kopplat till företaget. Använd knappen nedan för att logga in.`,
      joinedDiscount: (percent: string) => `Du får ${percent} % rabatt på det du köper när du är inloggad.`,
      joinedButton: "Logga in",
      joinedLinkNote: "Länken fungerar en gång och i sju dagar. Därefter kan du logga in med en kod från Mitt konto.",
      endedSubject: (company: string) => `Du är inte längre med i ${company}`,
      endedHeading: "Din företagsrabatt har avslutats",
      endedIntro: (company: string, store: string) =>
        `Du är inte längre kopplad till ${company} hos ${store}, så företagsrabatten gäller inte längre. Ditt konto och dina beställningar är som förut.`,
    },
    reminderSubject: (store: string, date: string) => `Din prenumeration hos ${store} förnyas ${date}`,
    reminderHeading: "Påminnelse om förnyelse",
    reminderIntro: (date: string, amount: string) =>
      `Din prenumeration förnyas ${date} och du debiteras ${amount}.`,
    reminderChange: "Du kan hoppa över, pausa, ändra eller säga upp före dess.",
    trialSubject: (store: string, date: string) => `Din provperiod hos ${store} slutar ${date}`,
    trialHeading: "Provperioden närmar sig sitt slut",
    trialIntro: (date: string, amount: string) =>
      `Provperioden slutar ${date}. Därefter fortsätter prenumerationen och du debiteras ${amount}.`,
    changedSubject: (store: string) => `Din prenumeration hos ${store} har ändrats`,
    changedHeading: "Prenumerationen har ändrats",
    changes: {
      cancel: (date: string) => `Prenumerationen avslutas ${date}. Du debiteras inte mer.`,
      resume: () => "Prenumerationen fortsätter som tidigare.",
      cancel_now: () => "Prenumerationen är avslutad.",
      pause: (date: string) => `Prenumerationen är pausad till ${date}.`,
      unpause: () => "Pausen är avslutad och prenumerationen fortsätter.",
      skip: (date: string) => `Nästa leverans hoppas över. Nästa debitering blir ${date}.`,
      change: () => "Innehållet i prenumerationen ändras från nästa förnyelse.",
    },
  },
  da: {
    deliveries: {
      startedSubject: (store: string) => `Din abonnementsboks fra ${store} er klar`,
      startedHeading: "Din abonnementsboks er klar",
      startedIntro: (day: string, cutoff: string) =>
        `Vi leverer din liste hver ${day}. Du kan ændre den indtil ${cutoff} før hver levering; ændringer derefter gælder den næste.`,
      startedCharge:
        "Vi trækker dit kort for hver levering, når den er på vej, for det den indeholder til dagens priser. Ændrer du intet, bliver næste levering som den forrige.",
      startedCancel: "Du kan springe en levering over, sætte den på pause eller afslutte når som helst på siden for din abonnementsboks.",
      preparedSubject: (store: string, date: string) => `Din levering fra ${store} ${date}`,
      preparedHeading: "Næste levering",
      preparedIntro: (date: string) => `Din levering ${date} bliver pakket nu.`,
      preparedCharge: (amount: string) => `Vi trækker ${amount} på dit kort, når den er på vej.`,
      leftOutHeading: "Ikke med denne gang",
      leftOutLine: (title: string, wanted: number, got: number) => (got > 0 ? `${title}: ${got} af ${wanted}` : `${title}: udsolgt`),
      nothingIntro: (date: string) =>
        `Intet på din liste kunne fås til leveringen ${date}, så der er ingen levering og intet træk denne gang.`,
      manage: "Se eller ændr din abonnementsboks",
      cardSubject: (store: string, number: string) => `Betal leveringen ${number} fra ${store}`,
      cardHeading: "Dit kort blev ikke trukket",
      cardIntro: (number: string, amount: string) =>
        `Vi kunne ikke trække ${amount} for leveringen ${number}. Betal her; kortet du betaler med, bruges til de næste leveringer.`,
      payNow: "Betal leveringen",
    },
    orderSubject: (store: string, number: string) => `Ordrebekræftelse ${number} fra ${store}`,
    orderHeading: "Tak for din bestilling!",
    orderIntro: (number: string) => `Vi har modtaget betalingen for ordre ${number}.`,
    renewalSubject: (store: string, number: string) => `Dit abonnement er fornyet: ordre ${number} fra ${store}`,
    renewalIntro: (number: string) => `Dit abonnement er fornyet, og ordre ${number} er betalt.`,
    subtotal: "Varer i alt",
    discount: "Rabat",
    shipping: "Fragt",
    total: "I alt",
    vat: "heraf moms",
    deliverTo: "Leveres til",
    seeOrder: "Se bestillingen",
    downloadsReady: "Dine filer er klar til download fra bestillingssiden.",
    subscription: (every: string, amount: string) =>
      `Abonnement: fornyes ${every.toLowerCase()} for ${amount}, indtil du opsiger det.`,
    manageSubscription: "Se eller ændr abonnementet",
    account: "Min konto",
    questions: (email: string) => `Spørgsmål? Svar på denne mail, eller skriv til ${email}.`,
    shippedSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er sendt`,
    shippedHeading: "Pakken er på vej!",
    shippedIntro: (number: string) => `Ordre ${number} er sendt.`,
    tracking: (carrier: string, number: string) => `Sporing: ${carrier} ${number}`.trim(),
    trackParcel: "Spor pakken",
    refundSubject: (store: string, number: string) => `Refundering for ordre ${number} fra ${store}`,
    refundHeading: "Vi har refunderet dig",
    refundIntro: (amount: string, number: string) =>
      `Vi har refunderet ${amount} for ordre ${number}. Der går normalt 5–10 bankdage, før beløbet er tilbage på din konto.`,
    cancelledSubject: (store: string, number: string) => `Ordre ${number} fra ${store} er annulleret`,
    cancelledHeading: "Bestillingen er annulleret",
    cancelledIntro: (number: string, amount: string) =>
      `Ordre ${number} er annulleret, og ${amount} er refunderet.`,
    cancelledUnpaidIntro: (number: string) => `Ordre ${number} er annulleret. Intet blev trukket.`,
    /** Appointments (D65). */
    bookingMovedSubject: (store: string, when: string) => `Ny tid hos ${store}: ${when}`,
    bookingMovedHeading: "Tiden er flyttet",
    bookingMovedIntro: (when: string) => `Din tid er nu ${when}.`,
    bookingCancelledByYouSubject: (store: string, when: string) => `Du har afbestilt tiden ${when} hos ${store}`,
    bookingCancelledByYouHeading: "Tiden er afbestilt",
    bookingCancelledByYouIntro: (service: string, when: string, refund: string | null) =>
      `Du har afbestilt ${service} ${when}.${refund ? ` Vi betaler ${refund} tilbage; det tager normalt 5–10 hverdage.` : ""}`,
    appointmentsHeading: "Din tid",
    calendarNote: "Tilføj tiden til din kalender med vedhæftningen.",
    bookingReminderSubject: (store: string, when: string) => `Påmindelse: din tid hos ${store} ${when}`,
    bookingReminderHeading: "Vi ses snart",
    bookingReminderIntro: (when: string) => `Dette er en påmindelse om din tid ${when}.`,
    bookingCancelledSubject: (store: string, when: string) => `Din tid hos ${store} ${when} er aflyst`,
    bookingCancelledHeading: "Tiden er aflyst",
    bookingCancelledIntro: (service: string, when: string) =>
      `Vi har desværre måttet aflyse ${service} ${when}. Svar på denne e-mail, hvis du vil have en ny tid eller har spørgsmål om betalingen.`,
    codeSubject: (store: string) => `Loginkode til ${store}`,
    codeHeading: "Din loginkode",
    codeIntro: "Indtast koden for at logge ind. Den virker i 10 minutter.",
    codeIgnore: "Bad du ikke om koden? Så kan du se bort fra denne mail.",
    resetSubject: (store: string) => `Ny adgangskode hos ${store}`,
    resetHeading: "Koden til ny adgangskode",
    resetIntro: "Indtast koden, og vælg en ny adgangskode. Den virker i 10 minutter.",
    welcomeSubject: (store: string) => `Velkommen til ${store}`,
    welcomeHeading: "Din konto er klar",
    welcomeIntro: (email: string) => `Du logger ind på Min konto med ${email} og den adgangskode, du valgte. Der ser du ordrer og abonnementer og kan ændre dine oplysninger.`,
    welcomeButton: "Gå til Min konto",
    welcomeIgnore: "Oprettede du ikke kontoen? Svar på denne mail, så sletter butikken den.",
    company: {
      inviteSubject: (company: string, store: string) => `${company} inviterer dig til ${store}`,
      inviteHeading: (company: string) => `Du er inviteret til ${company}`,
      inviteIntro: (inviter: string, company: string, store: string) =>
        `${inviter} har inviteret dig til at være med i ${company}s konto hos ${store}.`,
      inviteDiscount: (percent: string) => `Som medarbejder får du ${percent} % rabat på det, du køber.`,
      inviteButton: "Acceptér invitationen",
      inviteExpires: (date: string) => `Invitationen kan accepteres til ${date}.`,
      inviteIgnore: "Ventede du ikke denne? Ignorer mailen, så sker der intet, før du accepterer.",
      joinedSubject: (store: string) => `Du er med hos ${store}`,
      joinedHeading: (company: string) => `Du er nu med i ${company}`,
      joinedNew: (email: string) => `Vi har oprettet en konto til ${email}. Brug knappen nedenfor til at logge ind.`,
      joinedExisting: (email: string) => `Din konto (${email}) er nu knyttet til virksomheden. Brug knappen nedenfor til at logge ind.`,
      joinedDiscount: (percent: string) => `Du får ${percent} % rabat på det, du køber, når du er logget ind.`,
      joinedButton: "Log ind",
      joinedLinkNote: "Linket virker én gang og i syv dage. Bagefter kan du logge ind med en kode fra Min konto.",
      endedSubject: (company: string) => `Du er ikke længere med i ${company}`,
      endedHeading: "Din virksomhedsrabat er ophørt",
      endedIntro: (company: string, store: string) =>
        `Du er ikke længere knyttet til ${company} hos ${store}, så virksomhedsrabatten gælder ikke længere. Din konto og dine ordrer er som før.`,
    },
    reminderSubject: (store: string, date: string) => `Dit abonnement hos ${store} fornyes ${date}`,
    reminderHeading: "Påmindelse om fornyelse",
    reminderIntro: (date: string, amount: string) =>
      `Dit abonnement fornyes ${date}, og du bliver opkrævet ${amount}.`,
    reminderChange: "Du kan springe over, sætte på pause, ændre eller opsige inden da.",
    trialSubject: (store: string, date: string) => `Din prøveperiode hos ${store} slutter ${date}`,
    trialHeading: "Prøveperioden nærmer sig sin afslutning",
    trialIntro: (date: string, amount: string) =>
      `Prøveperioden slutter ${date}. Derefter fortsætter abonnementet, og du bliver opkrævet ${amount}.`,
    changedSubject: (store: string) => `Dit abonnement hos ${store} er ændret`,
    changedHeading: "Abonnementet er ændret",
    changes: {
      cancel: (date: string) => `Abonnementet slutter ${date}. Du bliver ikke opkrævet mere.`,
      resume: () => "Abonnementet fortsætter som før.",
      cancel_now: () => "Abonnementet er afsluttet.",
      pause: (date: string) => `Abonnementet er sat på pause til ${date}.`,
      unpause: () => "Pausen er slut, og abonnementet fortsætter.",
      skip: (date: string) => `Næste levering springes over. Næste opkrævning bliver ${date}.`,
      change: () => "Indholdet i abonnementet ændres fra næste fornyelse.",
    },
  },
  en: {
    deliveries: {
      startedSubject: (store: string) => `Your subscription box from ${store} is set up`,
      startedHeading: "Your subscription box is set up",
      startedIntro: (day: string, cutoff: string) =>
        `We deliver your list every ${day}. Change it until ${cutoff} before each delivery; changes after that go into the next one.`,
      startedCharge:
        "We charge your card for each delivery when it is on its way, for what it holds at that day's prices. If you change nothing, the next delivery is the same as the last.",
      startedCancel: "You can skip a delivery, pause or end your subscription box at any time on its page.",
      preparedSubject: (store: string, date: string) => `Your delivery from ${store} on ${date}`,
      preparedHeading: "Your next delivery",
      preparedIntro: (date: string) => `Your delivery on ${date} is being packed.`,
      preparedCharge: (amount: string) => `We charge ${amount} to your card when it is on its way.`,
      leftOutHeading: "Not in this delivery",
      leftOutLine: (title: string, wanted: number, got: number) => (got > 0 ? `${title}: ${got} of ${wanted}` : `${title}: sold out`),
      nothingIntro: (date: string) =>
        `Nothing on your list could be had for the delivery on ${date}, so there is no delivery and no charge this time.`,
      manage: "See or change your subscription box",
      cardSubject: (store: string, number: string) => `Please pay for your delivery ${number} from ${store}`,
      cardHeading: "Your card was not charged",
      cardIntro: (number: string, amount: string) =>
        `We could not charge ${amount} for delivery ${number}. Please pay here; the card you pay with is used for your next deliveries.`,
      payNow: "Pay for the delivery",
    },
    orderSubject: (store: string, number: string) => `Order confirmation ${number} from ${store}`,
    orderHeading: "Thank you for your order!",
    orderIntro: (number: string) => `We have received the payment for order ${number}.`,
    renewalSubject: (store: string, number: string) => `Your subscription has renewed: order ${number} from ${store}`,
    renewalIntro: (number: string) => `Your subscription has renewed, and order ${number} is paid.`,
    subtotal: "Subtotal",
    discount: "Discount",
    shipping: "Shipping",
    total: "Total",
    vat: "incl. VAT",
    deliverTo: "Delivered to",
    seeOrder: "See the order",
    downloadsReady: "Your files are ready to download from the order page.",
    subscription: (every: string, amount: string) =>
      `Subscription: renews ${every.toLowerCase()} at ${amount} until you cancel.`,
    manageSubscription: "See or change the subscription",
    account: "My account",
    questions: (email: string) => `Questions? Reply to this email or write to ${email}.`,
    shippedSubject: (store: string, number: string) => `Order ${number} from ${store} is on its way`,
    shippedHeading: "Your parcel is on its way!",
    shippedIntro: (number: string) => `Order ${number} has been sent.`,
    tracking: (carrier: string, number: string) => `Tracking: ${carrier} ${number}`.trim(),
    trackParcel: "Track the parcel",
    refundSubject: (store: string, number: string) => `Refund for order ${number} from ${store}`,
    refundHeading: "We have refunded you",
    refundIntro: (amount: string, number: string) =>
      `We have refunded ${amount} for order ${number}. It usually takes 5–10 working days to reach your account.`,
    cancelledSubject: (store: string, number: string) => `Order ${number} from ${store} is cancelled`,
    cancelledHeading: "Your order is cancelled",
    cancelledIntro: (number: string, amount: string) =>
      `Order ${number} is cancelled and ${amount} has been refunded.`,
    cancelledUnpaidIntro: (number: string) => `Order ${number} is cancelled. Nothing was charged.`,
    /** Appointments (D65). */
    bookingMovedSubject: (store: string, when: string) => `New time at ${store}: ${when}`,
    bookingMovedHeading: "Your appointment has moved",
    bookingMovedIntro: (when: string) => `Your appointment is now on ${when}.`,
    bookingCancelledByYouSubject: (store: string, when: string) => `You have cancelled your appointment on ${when} at ${store}`,
    bookingCancelledByYouHeading: "Your appointment is cancelled",
    bookingCancelledByYouIntro: (service: string, when: string, refund: string | null) =>
      `You have cancelled ${service} on ${when}.${refund ? ` We are paying back ${refund}; it usually takes 5–10 working days.` : ""}`,
    appointmentsHeading: "Your appointment",
    calendarNote: "Add it to your calendar with the attached file.",
    bookingReminderSubject: (store: string, when: string) => `Reminder: your appointment at ${store}, ${when}`,
    bookingReminderHeading: "See you soon",
    bookingReminderIntro: (when: string) => `This is a reminder of your appointment on ${when}.`,
    bookingCancelledSubject: (store: string, when: string) => `Your appointment at ${store} on ${when} is cancelled`,
    bookingCancelledHeading: "Your appointment is cancelled",
    bookingCancelledIntro: (service: string, when: string) =>
      `We have had to cancel ${service} on ${when}. Reply to this email to book a new time or with any questions about your payment.`,
    codeSubject: (store: string) => `Sign-in code for ${store}`,
    codeHeading: "Your sign-in code",
    codeIntro: "Enter the code to sign in. It works for 10 minutes.",
    codeIgnore: "Did not ask for this code? You can ignore this email.",
    resetSubject: (store: string) => `New password at ${store}`,
    resetHeading: "Your code for a new password",
    resetIntro: "Enter the code and choose a new password. It works for 10 minutes.",
    welcomeSubject: (store: string) => `Welcome to ${store}`,
    welcomeHeading: "Your account is ready",
    welcomeIntro: (email: string) => `Sign in to My account with ${email} and the password you chose. There you see your orders and subscriptions, and can change your details.`,
    welcomeButton: "Go to My account",
    welcomeIgnore: "Did not open this account? Reply to this email and the store deletes it.",
    company: {
      inviteSubject: (company: string, store: string) => `${company} invites you to ${store}`,
      inviteHeading: (company: string) => `You are invited to ${company}`,
      inviteIntro: (inviter: string, company: string, store: string) =>
        `${inviter} has invited you to join the ${company} account at ${store}.`,
      inviteDiscount: (percent: string) => `As an employee you get ${percent} % off what you buy.`,
      inviteButton: "Accept the invitation",
      inviteExpires: (date: string) => `The invitation can be accepted until ${date}.`,
      inviteIgnore: "Not expecting this? Ignore the email and nothing happens until you accept.",
      joinedSubject: (store: string) => `You have joined at ${store}`,
      joinedHeading: (company: string) => `You are now part of ${company}`,
      joinedNew: (email: string) => `We have opened an account for ${email}. Use the button below to sign in.`,
      joinedExisting: (email: string) => `Your account (${email}) is now linked to the company. Use the button below to sign in.`,
      joinedDiscount: (percent: string) => `You get ${percent} % off what you buy while you are signed in.`,
      joinedButton: "Sign in",
      joinedLinkNote: "The link works once, for seven days. After that you can sign in with a code from My account.",
      endedSubject: (company: string) => `You are no longer part of ${company}`,
      endedHeading: "Your company discount has ended",
      endedIntro: (company: string, store: string) =>
        `You are no longer linked to ${company} at ${store}, so the company discount no longer applies. Your account and orders are as before.`,
    },
    reminderSubject: (store: string, date: string) => `Your subscription at ${store} renews on ${date}`,
    reminderHeading: "Renewal reminder",
    reminderIntro: (date: string, amount: string) =>
      `Your subscription renews on ${date}, and you will be charged ${amount}.`,
    reminderChange: "You can skip, pause, change or cancel before then.",
    trialSubject: (store: string, date: string) => `Your trial at ${store} ends on ${date}`,
    trialHeading: "Your trial is ending soon",
    trialIntro: (date: string, amount: string) =>
      `Your trial ends on ${date}. The subscription then continues, and you will be charged ${amount}.`,
    changedSubject: (store: string) => `Your subscription at ${store} has changed`,
    changedHeading: "Your subscription has changed",
    changes: {
      cancel: (date: string) => `The subscription ends on ${date}. You will not be charged again.`,
      resume: () => "The subscription continues as before.",
      cancel_now: () => "The subscription has ended.",
      pause: (date: string) => `The subscription is paused until ${date}.`,
      unpause: () => "The pause is over and the subscription continues.",
      skip: (date: string) => `The next delivery is skipped. The next charge is on ${date}.`,
      change: () => "What the subscription holds changes from the next renewal.",
    },
  },
};

export type EmailText = (typeof text)["en"];

export function emailText(lang: string): EmailText {
  return lang in text ? text[lang as keyof typeof text] : text.en;
}
