/**
 * The icons an icon list offers (D91), by name, with what each is called
 * in the editor. Drawn by `ListIcon` (Lucide's, ISC); pure, so the schema
 * knows the names without the drawings.
 */
export const ICONS = {
  check: "Tick",
  circleCheck: "Tick in a circle",
  x: "Cross",
  plus: "Plus",
  minus: "Minus",
  arrowRight: "Arrow",
  chevronRight: "Chevron",
  star: "Star",
  heart: "Heart",
  thumbsUp: "Thumbs up",
  smile: "Smile",
  sparkles: "Sparkles",
  award: "Award",
  trophy: "Trophy",
  truck: "Delivery",
  package: "Parcel",
  gift: "Gift",
  rotateCcw: "Returns",
  shieldCheck: "Shield",
  lock: "Lock",
  creditCard: "Card",
  wallet: "Wallet",
  tag: "Tag",
  percent: "Percent",
  shoppingBag: "Shopping bag",
  shoppingCart: "Cart",
  store: "Shop",
  house: "Home",
  clock: "Clock",
  calendar: "Calendar",
  mapPin: "Place",
  phone: "Phone",
  mail: "Email",
  messageCircle: "Message",
  headphones: "Support",
  globe: "Globe",
  info: "Information",
  circleHelp: "Question",
  circleAlert: "Warning",
  users: "People",
  user: "Person",
  leaf: "Leaf",
  sprout: "Sprout",
  recycle: "Recycle",
  droplet: "Drop",
  sun: "Sun",
  snowflake: "Snowflake",
  flame: "Flame",
  zap: "Lightning",
  coffee: "Coffee",
  utensils: "Food",
  scissors: "Scissors",
  wrench: "Tools",
  paintbrush: "Brush",
  camera: "Camera",
  music: "Music",
  book: "Book",
  graduationCap: "Learning",
  car: "Car",
  bike: "Bicycle",
  plane: "Plane",
  mountain: "Mountain",
  waves: "Waves",
  pawPrint: "Paw",
  baby: "Baby",
  wifi: "Wi-Fi",
} as const;
export type IconName = keyof typeof ICONS;
