import {
  ArrowRight,
  Award,
  Baby,
  Bike,
  Book,
  Calendar,
  Camera,
  Car,
  Check,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  Clock,
  Coffee,
  CreditCard,
  Droplet,
  Flame,
  Gift,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  House,
  Info,
  Leaf,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Minus,
  Mountain,
  Music,
  Package,
  Paintbrush,
  PawPrint,
  Percent,
  Phone,
  Plane,
  Plus,
  Recycle,
  RotateCcw,
  Scissors,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Store,
  Sun,
  Tag,
  ThumbsUp,
  Trophy,
  Truck,
  User,
  Users,
  Utensils,
  Wallet,
  Waves,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

import type { CSSProperties } from "react";

import type { IconName } from "@/lib/icons";

const DRAWINGS: Record<IconName, LucideIcon> = {
  check: Check,
  circleCheck: CircleCheck,
  x: X,
  plus: Plus,
  minus: Minus,
  arrowRight: ArrowRight,
  chevronRight: ChevronRight,
  star: Star,
  heart: Heart,
  thumbsUp: ThumbsUp,
  smile: Smile,
  sparkles: Sparkles,
  award: Award,
  trophy: Trophy,
  truck: Truck,
  package: Package,
  gift: Gift,
  rotateCcw: RotateCcw,
  shieldCheck: ShieldCheck,
  lock: Lock,
  creditCard: CreditCard,
  wallet: Wallet,
  tag: Tag,
  percent: Percent,
  shoppingBag: ShoppingBag,
  shoppingCart: ShoppingCart,
  store: Store,
  house: House,
  clock: Clock,
  calendar: Calendar,
  mapPin: MapPin,
  phone: Phone,
  mail: Mail,
  messageCircle: MessageCircle,
  headphones: Headphones,
  globe: Globe,
  info: Info,
  circleHelp: CircleHelp,
  circleAlert: CircleAlert,
  users: Users,
  user: User,
  leaf: Leaf,
  sprout: Sprout,
  recycle: Recycle,
  droplet: Droplet,
  sun: Sun,
  snowflake: Snowflake,
  flame: Flame,
  zap: Zap,
  coffee: Coffee,
  utensils: Utensils,
  scissors: Scissors,
  wrench: Wrench,
  paintbrush: Paintbrush,
  camera: Camera,
  music: Music,
  book: Book,
  graduationCap: GraduationCap,
  car: Car,
  bike: Bike,
  plane: Plane,
  mountain: Mountain,
  waves: Waves,
  pawPrint: PawPrint,
  baby: Baby,
  wifi: Wifi,
};

/** An icon list's icon (D91), in the current colour; decorative, as the text beside it says what it means. */
export function ListIcon({ name, className, style }: { name: IconName; className?: string; style?: CSSProperties }) {
  const Drawing = DRAWINGS[name] ?? Check;
  return <Drawing aria-hidden focusable={false} className={className} style={style} strokeWidth={2} />;
}
