/**
 * Juridiske startertekster på dansk (bølge 1, 1e). SKREVET I HÅND, aldrig maskinoversat, og IKKE juridisk rådgivning: et
 * udgangspunkt lavet af butikkens egne oplysninger, som et menneske skal læse, rette og færdiggøre før brug. Hver sætning
 * her skal gennemgås juridisk af en person (docs/wave-1-trust.md afsnit 8). `{name}` er stedet, hvor butikkens egne
 * oplysninger sættes ind; `[[Tilføj: …]]` og `[[Kontrollér: …]]` er pladsholdere, som butikken skal tage stilling til.
 * Sidernes form er i `../legal-starters.ts`. Modelfortrydelsesformularen følger direktivets bilag I(B) i indhold, men er ikke
 * kopieret fra den officielle danske tekst: kontrollér mod den.
 */
import type { StarterText } from "../legal-starters";

export const DA: StarterText = {
  language: "da",
  locale: "da-DK",
  m: {
    notice:
      "UDKAST: skal gennemgås juridisk før brug. Kaizen Store har lavet denne tekst af butikkens oplysninger som et udgangspunkt. Den er ikke juridisk rådgivning, og ingen jurist har kontrolleret den. Læs hver sætning, udfyld delene i [[klammer]], og slet denne note, når du har gjort det.",
    "notice.language": "Denne tekst er på dansk, fordi den ikke findes på butikkens sprog: lad en person oversætte og gennemgå den før brug.",
    "ph.add": "Tilføj",
    "ph.check": "Kontrollér",

    "label.storeName": "butikkens navn",
    "label.legalName": "virksomhedens juridiske navn",
    "label.orgNumber": "CVR-nummer eller organisationsnummer",
    "label.vatNumber": "momsnummer",
    "label.address": "postadresse",
    "label.email": "e-mailadresse til kontakt",
    "label.phone": "telefonnummer",
    "label.country": "land",
    "label.markets": "de lande I sælger til",
    "label.currency": "valuta",
    "label.shippingPrice": "fragtpris",
    "label.carriers": "fragtfirmaer",
    "label.contractFormation": "hvornår aftalen indgås: når bestillingen afgives, eller når I bekræfter den",
    "label.deliveryTime": "leveringstid",
    "label.guaranteePeriod": "reklamationsfrist",
    "label.complaintBody": "forbrugerklageorganet i dit land",
    "label.legalReferences": "de forbrugerlove, der gælder i dit land, og hvilken domstol der afgør tvister",
    "label.transfers": "hvor hver modtager behandler oplysningerne, og hvilke garantier der gælder, når oplysninger forlader EU/EØS",
    "label.retentionPeriod": "hvor længe ordre- og regnskabsoplysninger opbevares, i år",
    "label.dataAuthority": "databeskyttelsesmyndigheden i dit land, for eksempel Datatilsynet i Norge, IMY i Sverige eller Datatilsynet i Danmark",
    "label.aiProvider": "den AI-leverandør, chatassistenten bruger",
    "label.returnInstructions": "hvordan varer returneres: hvor de sendes hen, og hvordan de pakkes",
    "label.returnAddress": "returadresse",
    "label.outsideEu": "om I leverer uden for EU, og hvem der betaler told, afgifter og importmoms",
    "label.damagedDays": "inden for hvor mange dage kunden skal melde beskadigede varer",
    "label.exclusionsFit": "hvilke af undtagelserne her der gælder det, I sælger: slet resten",
    "label.tradeRegister": "handelsregister og registreringsnummer, hvis virksomheden er optaget i et",
    "label.supervisoryAuthority": "tilsynsmyndigheden, hvis virksomheden har brug for tilladelse eller er under tilsyn",

    "title.terms": "Handelsbetingelser",
    "title.privacy": "Privatlivspolitik",
    "title.returns_policy": "Returpolitik",
    "title.shipping_policy": "Fragt og levering",
    "title.withdrawal_info": "Oplysninger om fortrydelsesret",
    "title.imprint": "Om virksomheden",
    "slug.terms": "handelsbetingelser",
    "slug.privacy": "privatlivspolitik",
    "slug.returns_policy": "returpolitik",
    "slug.shipping_policy": "fragt-og-levering",
    "slug.withdrawal_info": "fortrydelsesret",
    "slug.imprint": "om-virksomheden",

    "vat.yes": "Momsnummer: {vat}.",
    "vat.no": "Virksomheden er ikke momsregistreret.",
    "rate.plain": "{country}: {rate}.",
    "rate.free": "{country}: {rate}, og gratis for bestillinger over {amount}.",
    "rate.zero": "{country}: gratis.",
    "rate.none": "{country}: {check}",
    "carriers.some": "Vi sender varerne med {carriers}.",
    "carriers.none": "De fragtfirmaer, vi bruger: {check}",
    "excl.custom_made": "varer, der er fremstillet efter dine specifikationer eller tydeligt tilpasset dig personligt",
    "excl.perishable": "varer, der hurtigt fordærves, eller hvis holdbarhed hurtigt udløber",
    "excl.sealed_hygiene": "forseglede varer, der af sundheds- eller hygiejnemæssige grunde ikke egner sig til returnering, hvis forseglingen er brudt",
    "excl.sealed_media": "forseglede lyd- eller billedoptagelser og software, hvis forseglingen er brudt",
    "excl.mixed": "varer, der efter leveringen i kraft af deres natur uigenkaldeligt er blandet med andre varer",
    "excl.price_fluctuation": "varer, hvis pris afhænger af udsving på finansmarkedet, som vi ikke har indflydelse på",
    "excl.alcohol": "alkoholholdige drikkevarer, hvis pris blev aftalt ved bestillingen, men som først kan leveres efter 30 dage",
    "excl.periodicals": "aviser, tidsskrifter og blade, bortset fra abonnementer på dem",
    "excl.digital": "digitalt indhold, der ikke leveres på et fysisk medium, når leveringen er påbegyndt med dit forudgående samtykke",
    "excl.dated_service": "indkvartering, der ikke er til beboelse, godstransport, biludlejning, forplejning eller fritidsaktiviteter, hvis aftalen angiver en bestemt dato eller periode for tjenesteydelsen",
    "excl.service_performed": "tjenesteydelser, der er fuldt udført, hvis udførelsen begyndte med dit udtrykkelige forudgående samtykke, og du har bekræftet, at du mister fortrydelsesretten, når tjenesteydelsen er fuldt udført",
    "excl.check": "{check}",

    "h.terms.seller": "Hvem vi er",
    "terms.seller.1": "Disse betingelser gælder for køb hos {store}, som drives af {name}, organisationsnummer {org}.",
    "terms.seller.2": "Adresse: {address}. E-mail: {email}. Telefon: {phone}.",
    "h.terms.products_prices": "Varer og priser",
    "terms.products.1": "De vigtigste egenskaber ved hvert produkt er beskrevet på produktsiden. Læs dem, før du bestiller.",
    "terms.products.2": "Priserne vises i {currencies}, for det land du handler i. For forbrugere er priserne angivet inklusive moms.",
    "h.terms.vat_shipping_costs": "Moms og leveringsomkostninger",
    "terms.costs.1": "Den samlede pris, med moms og leveringsomkostninger, vises, før du afgiver din bestilling. Leveringsomkostninger for hvert land:",
    "terms.costs.none": "Leveringsomkostninger: {check}",
    "h.terms.order_contract": "Når du bestiller",
    "terms.order.1": "Når du trykker på knappen for at bestille, afgiver du en bindende bestilling og forpligter dig til at betale.",
    "terms.order.2": "Vi bekræfter din bestilling på e-mail. {check}",
    "terms.order.3": "Den version af disse betingelser, der gjaldt, da du bestilte, gemmes sammen med din bestilling, så vi kan vise den til dig senere.",
    "h.terms.payment": "Betaling",
    "terms.payment.1": "Betalingen går gennem vores betalingsleverandør, Stripe, som håndterer dine kortoplysninger eller andre betalingsoplysninger. Vi ser aldrig dit fulde kortnummer. De betalingsmåder, der tilbydes, vises i kassen.",
    "h.terms.delivery": "Levering",
    "terms.delivery.1": "Vi leverer til: {markets}.",
    "terms.delivery.2": "Leveringstid: {check}",
    "h.terms.withdrawal": "Fortrydelsesret",
    "terms.withdrawal.1": "Er du forbruger, har du ret til at fortryde købet inden for 14 dage fra den dag, du modtager varerne, uden at angive en grund, bortset fra det, der er nævnt i oplysningerne om fortrydelsesret.",
    "terms.withdrawal.services": "For tjenesteydelser, for eksempel en booking, løber de 14 dage fra den dag, aftalen blev indgået.",
    "terms.withdrawal.regular": "For en abonnementskasse (regelmæssig levering af varer) løber de 14 dage fra den dag, du modtager den første levering.",
    "terms.withdrawal.link": "Læs oplysningerne om fortrydelsesret og [brug fortrydelsesfunktionen]({href}).",
    "terms.withdrawal.nolink": "Læs oplysningerne om fortrydelsesret på dette website for at se, hvordan du bruger retten.",
    "h.terms.returns_link": "Returnering",
    "terms.returns.1": "Du kan returnere varer inden for {days} dage efter, at du har modtaget dem. Se returpolitikken for, hvordan.",
    "terms.returns.shopper": "Når du returnerer varer, betaler du de direkte omkostninger ved at sende dem tilbage, medmindre vi siger andet.",
    "terms.returns.store": "Vi betaler omkostningen ved at sende returnerede varer tilbage til os.",
    "h.terms.conformity": "Fejl og mangler",
    "terms.conformity.1": "Varerne skal være som aftalt. Er de ikke det, har du de rettigheder, som den lovbestemte garanti i dit land giver dig. Rettighederne gælder ud over det, vi selv tilbyder.",
    "terms.conformity.2": "Reklamationsfrist: {check}",
    "h.terms.complaints": "Reklamation",
    "terms.complaints.1": "Er noget galt, så skriv til os på {email}, så snart du opdager det.",
    "terms.complaints.2": "{check}",
    "h.terms.disputes": "Hvis vi ikke bliver enige",
    "terms.disputes.1": "Hvis vi ikke kan blive enige om en klage, kan du henvende dig til {check}",
    "h.terms.privacy_link": "Personoplysninger",
    "terms.privacy.1": "Hvordan vi behandler dine personoplysninger, er beskrevet i vores privatlivspolitik.",
    "h.terms.bookings_subscriptions": "Bookinger og abonnementskasser",
    "terms.bookings.1": "Aftaler, ophold og udlejning bestilles til et bestemt tidspunkt. Du kan aflyse eller flytte en booking frem til den frist, der vises, når du booker.",
    "terms.bookings.2": "En abonnementskasse leveres på de viste dage og fortsætter, til du stopper den. Du kan ændre, sætte på pause eller afslutte den frem til den frist, der vises før hver levering.",
    "h.terms.businesses": "Køb fra virksomheder",
    "terms.business.1": "Disse betingelser gælder også, når en virksomhed køber hos os. Virksomheder ser priser uden moms, men moms lægges til bestillingen, hvor den gælder.",
    "terms.business.returns": "Den lovbestemte fortrydelsesret gælder for forbrugere. For virksomheder tilbyder vi returnering af varer, som beskrevet i returpolitikken.",
    "terms.business.noreturns": "Den lovbestemte fortrydelsesret gælder for forbrugere og gælder ikke, når en virksomhed køber.",
    "h.terms.law_and_changes": "Lovvalg og ændringer",
    "terms.law.1": "Disse betingelser er underlagt lovgivningen i {country}.",
    "terms.law.2": "{check}",
    "terms.law.3": "Vi kan ændre disse betingelser. Den version, der gjaldt, da du afgav din bestilling, er den, der gælder for den bestilling.",

    "h.privacy.controller": "Hvem der er ansvarlig",
    "privacy.controller.1": "{name}, organisationsnummer {org}, adresse {address}, driver {store} og er dataansvarlig for de personoplysninger, der er beskrevet her.",
    "privacy.controller.2": "Butikken kører på platformen Kaizen Store. Platformen behandler personoplysninger på vores vegne, som vores databehandler.",
    "h.privacy.contact": "Kontakt",
    "privacy.contact.1": "Spørgsmål om dine personoplysninger: {email}. Telefon: {phone}.",
    "h.privacy.purposes_basis": "Hvad vi bruger oplysningerne til",
    "privacy.purposes.1": "Vi bruger personoplysninger til disse formål, hvert på det retlige grundlag, der er angivet:",
    "privacy.purpose.orders": "at modtage, tage betaling for, levere og følge op på dine bestillinger, og at bekræfte og sende dig det, du har købt (opfyldelse af aftalen)",
    "privacy.purpose.accounting": "at føre regnskab og opbevare det materiale, loven kræver (retlig forpligtelse)",
    "privacy.purpose.service": "at besvare dine spørgsmål og reklamationer (opfyldelse af aftalen, og vores legitime interesse i at yde god service)",
    "privacy.purpose.security": "at holde butikken sikker og forebygge svindel og misbrug (vores legitime interesse)",
    "privacy.purpose.marketing": "at sende dig markedsføring på e-mail, kun hvis du har sagt ja til det (samtykke)",
    "privacy.purpose.visits": "at tælle besøg i butikken uden cookies, for at se, hvordan den bruges; vi gemmer ingen IP-adresse og ingen browseridentifikator (vores legitime interesse)",
    "h.privacy.recipients": "Hvem der får oplysningerne",
    "privacy.recipients.1": "Vi deler kun personoplysninger med dem, der har brug for dem:",
    "privacy.recipient.platform": "platformen Kaizen Store, som driver butikken og behandler oplysninger på vores vegne",
    "privacy.recipient.stripe": "Stripe, vores betalingsleverandør, som håndterer betalinger",
    "privacy.recipient.email": "den e-mailtjeneste, platformen bruger til at sende ordrebekræftelser og andre beskeder til dig",
    "privacy.recipient.carriers": "fragtfirmaer, der leverer dine varer: {carriers}",
    "privacy.recipient.carriers.none": "fragtfirmaer, der leverer dine varer: {check}",
    "privacy.recipient.tool": "{tool}, som butikken kun indlæser, hvis du accepterer de tilhørende cookies",
    "privacy.recipient.authorities": "offentlige myndigheder, når loven kræver, at vi videregiver oplysninger",
    "h.privacy.transfers": "Overførsel uden for EU/EØS",
    "privacy.transfers.1": "Platformen gemmer butikkens data i EU. Nogle af modtagerne ovenfor kan behandle oplysninger andre steder.",
    "privacy.transfers.2": "{check}",
    "h.privacy.retention": "Hvor længe vi opbevarer oplysningerne",
    "privacy.retention.1": "Ordre- og regnskabsoplysninger opbevares så længe, loven kræver: {check}",
    "privacy.retention.2": "Andre oplysninger opbevares kun, så længe vi har brug for dem til det formål, de blev indsamlet til. En kundekonto opbevares, til du sletter den.",
    "h.privacy.rights": "Dine rettigheder",
    "privacy.rights.1": "Du har ret til at:",
    "privacy.right.access": "bede om indsigt i de personoplysninger, vi har om dig",
    "privacy.right.rectify": "få urigtige oplysninger rettet",
    "privacy.right.erase": "få dine oplysninger slettet, hvor loven tillader det (materiale, vi skal opbevare efter loven, kan ikke slettes, før perioden er udløbet)",
    "privacy.right.restrict": "kræve, at brugen af dine oplysninger begrænses",
    "privacy.right.portability": "få dine oplysninger i et almindeligt format og få dem overført til en anden tjeneste",
    "privacy.right.object": "gøre indsigelse mod behandling, der bygger på vores legitime interesse",
    "h.privacy.consent_withdrawal": "Tilbagekaldelse af samtykke",
    "privacy.consent.1": "Hvor vi bruger dine oplysninger, fordi du har givet samtykke, kan du til enhver tid trække samtykket tilbage. Det påvirker ikke det, vi gjorde, før du trak det tilbage.",
    "h.privacy.complaint_authority": "Klage til myndigheden",
    "privacy.complaint.1": "Du kan klage over, hvordan vi behandler dine personoplysninger, til databeskyttelsesmyndigheden: {check}",
    "h.privacy.obligation_to_provide": "Skal du give os oplysningerne?",
    "privacy.obligation.1": "Du skal give os de oplysninger, vi har brug for for at indgå og levere din bestilling, som navn, adresse og e-mail. Uden dem kan vi ikke gennemføre købet. Alt andet er frivilligt.",
    "h.privacy.automated_decisions": "Automatiske afgørelser",
    "privacy.automated.1": "Vi træffer ikke afgørelser om dig, der udelukkende bygger på automatisk behandling, og som har retsvirkning eller tilsvarende betydelig indvirkning på dig.",
    "privacy.automated.chat": "Butikken har en chatassistent, der bruger kunstig intelligens til at besvare spørgsmål ud fra butikkens egne oplysninger. Det, du skriver til den, sendes til den AI-leverandør, butikken bruger ({check}). Skriv ikke følsomme personoplysninger til den.",
    "h.privacy.cookies_link": "Cookies",
    "privacy.cookies.link": "De cookies og lignende værktøjer, butikken bruger, er opført på [siden om cookies]({href}).",
    "privacy.cookies.nolink": "De cookies og lignende værktøjer, butikken bruger, er opført på butikkens side om cookies.",

    "h.returns_policy.window": "Hvor længe du har",
    "returns.window.1": "Du kan returnere varer inden for {days} dage fra den dag, du modtager dem.",
    "returns.window.extended": "Af disse er 14 dage din lovbestemte fortrydelsesret som forbruger. Resten, op til {days} dage, er vores egen længere returfrist, som vi tilbyder ud over det.",
    "h.returns_policy.how_to": "Sådan returnerer du",
    "returns.how.1": "Fortæl os først, at du vil returnere varer. Send dem derefter tilbage, som beskrevet nedenfor.",
    "returns.how.instructions": "{instructions}",
    "returns.how.noinstructions": "{check}",
    "h.returns_policy.who_pays": "Hvem der betaler for returneringen",
    "returns.pays.shopper": "Du betaler de direkte omkostninger ved at sende varerne tilbage, medmindre varerne var mangelfulde eller ikke som aftalt.",
    "returns.pays.store": "Vi betaler omkostningen ved at sende varerne tilbage.",
    "h.returns_policy.refund_timing": "Hvornår du får pengene tilbage",
    "returns.refund.received": "Vi tilbagebetaler det, du har betalt, inklusive standardlevering, senest 14 dage efter, at vi har fået kendskab til din beslutning. Vi kan vente, til vi har fået varerne tilbage, eller til du har dokumenteret, at du har sendt dem, alt efter hvad der sker først.",
    "returns.refund.request": "Vi tilbagebetaler det, du har betalt, inklusive standardlevering, senest 14 dage efter, at vi har fået kendskab til din beslutning.",
    "h.returns_policy.excluded_goods": "Varer, der ikke kan returneres",
    "returns.excluded.1": "Den lovbestemte fortrydelsesret gælder ikke for:",
    "returns.excluded.accept": "Vi tager alligevel nogle af disse varer tilbage inden for vores egen returfrist, hvis de er i den stand, vi beder om.",
    "returns.excluded.refuse": "Vi tager ikke disse varer tilbage.",
    "h.returns_policy.return_address": "Hvor returvarer sendes hen",
    "returns.address.1": "Send returvarer til: {address}.",
    "h.returns_policy.withdrawal_link": "At fortryde et køb",
    "returns.withdrawal.link": "For at fortryde et køb som forbruger skal du [bruge fortrydelsesfunktionen]({href}) eller læse oplysningerne om fortrydelsesret.",
    "returns.withdrawal.nolink": "For at fortryde et køb som forbruger skal du læse oplysningerne om fortrydelsesret på dette website.",
    "h.returns_policy.businesses": "Køb fra virksomheder",
    "returns.business.1": "Den lovbestemte fortrydelsesret gælder for forbrugere.",
    "returns.business.voluntary": "Virksomheder kan returnere varer på samme måde og inden for samme frist som andre kunder, som en service fra os og ikke som en lovbestemt ret.",
    "returns.business.none": "Den gælder ikke, når en virksomhed køber, og vi tager ikke varer tilbage fra virksomheder, medmindre vi aftaler andet.",

    "h.shipping_policy.markets": "Hvor vi leverer",
    "shipping.markets.1": "Vi leverer til: {markets}.",
    "h.shipping_policy.rates": "Hvad levering koster",
    "shipping.rates.1": "Leveringsomkostninger, med moms, for hvert land:",
    "shipping.rates.none": "Leveringsomkostninger: {check}",
    "h.shipping_policy.carriers": "Fragtfirmaer",
    "h.shipping_policy.delivery_time": "Hvor lang tid det tager",
    "shipping.time.1": "Leveringstid: {check}",
    "h.shipping_policy.tracking": "Sporing",
    "shipping.tracking.1": "Når din bestilling er sendt, får du en e-mail. Hvor fragtfirmaet tilbyder det, indeholder e-mailen et sporingslink.",
    "h.shipping_policy.outside_eu": "Uden for EU",
    "shipping.outside.1": "{check}",
    "h.shipping_policy.damaged_goods": "Beskadigede varer",
    "shipping.damaged.1": "Hvis varer ankommer beskadigede, så giv os besked {check}",
    "h.shipping_policy.contact": "Spørgsmål",
    "shipping.contact.1": "Spørgsmål om din levering: {email}.",

    "h.withdrawal_info.right": "Fortrydelsesret",
    "withdrawal.right.1": "Er du forbruger, har du ret til at fortryde denne aftale inden for 14 dage uden at angive en grund.",
    "withdrawal.right.2": "Fortrydelsesfristen udløber 14 dage efter den dag, hvor du, eller en tredjepart, som du har udpeget, og som ikke er transportøren, kommer i fysisk besiddelse af varerne. Bestiller du flere varer i én bestilling, som leveres hver for sig, udløber fristen 14 dage efter den dag, du modtager den sidste af dem.",
    "withdrawal.right.services": "For en aftale om tjenesteydelser, for eksempel en booking, udløber fortrydelsesfristen 14 dage efter den dag, aftalen blev indgået.",
    "withdrawal.right.regular": "For en aftale om regelmæssig levering af varer i en bestemt periode, for eksempel en abonnementskasse, udløber fortrydelsesfristen 14 dage efter den dag, du modtager den første levering.",
    "h.withdrawal_info.how": "Sådan fortryder du",
    "withdrawal.how.1": "For at gøre brug af fortrydelsesretten skal du give {name}, {address}, {email}, besked om, at du fortryder aftalen, i en utvetydig erklæring, for eksempel i et brev sendt med post eller på e-mail.",
    "withdrawal.how.online": "Du kan også [fortryde online]({href}) på dette website.",
    "withdrawal.how.noonline": "Du kan også bruge fortrydelsesfunktionen på dette website.",
    "withdrawal.how.2": "Du kan bruge modelfortrydelsesformularen nedenfor, men du behøver ikke. For at overholde fristen er det nok, at du sender din besked, før fortrydelsesfristen er udløbet.",
    "h.withdrawal_info.effects": "Hvad der sker, når du fortryder",
    "withdrawal.effects.1": "Fortryder du aftalen, tilbagebetaler vi alle betalinger, vi har modtaget fra dig, inklusive omkostningerne ved standardlevering, uden unødig forsinkelse og senest 14 dage efter den dag, vi får besked om din beslutning.",
    "withdrawal.effects.2": "Vi kan tilbageholde tilbagebetalingen, til vi har fået varerne tilbage, eller til du har dokumenteret, at du har sendt dem tilbage, alt efter hvad der sker først. Vi bruger samme betalingsmiddel, som du brugte ved bestillingen, medmindre du accepterer noget andet.",
    "withdrawal.effects.3": "Du skal sende varerne tilbage eller aflevere dem til os uden unødig forsinkelse og senest 14 dage efter den dag, du gav os besked om, at du fortryder.",
    "withdrawal.effects.pays.shopper": "Du betaler de direkte omkostninger ved at returnere varerne.",
    "withdrawal.effects.pays.store": "Vi betaler omkostningen ved at returnere varerne.",
    "withdrawal.effects.4": "Du hæfter kun for en eventuel nedsat værdi af varerne, der skyldes anden håndtering end den, der er nødvendig for at fastslå varernes art, egenskaber og funktion.",
    "withdrawal.effects.services": "Har du bedt om, at en tjenesteydelse skal begynde i fortrydelsesperioden, skal du betale os et beløb, der står i rimeligt forhold til det, der er leveret, indtil du meddelte os, at du fortryder, sammenlignet med aftalens fulde omfang.",
    "h.withdrawal_info.exclusions": "Hvornår der ikke er fortrydelsesret",
    "withdrawal.excl.1": "Der er ikke fortrydelsesret for:",
    "h.withdrawal_info.model_form": "Modelfortrydelsesformular",
    "withdrawal.form.1": "Udfyld og returnér kun denne formular, hvis du vil fortryde aftalen.",
    "withdrawal.form.to": "Til {name}, {address}, {email}:",
    "withdrawal.form.notice": "Jeg/vi (*) meddeler herved, at jeg/vi (*) fortryder min/vores (*) aftale om køb af følgende varer (*) / om levering af følgende tjenesteydelse (*),",
    "withdrawal.form.ordered": "Bestilt den (*) / modtaget den (*),",
    "withdrawal.form.consumer": "Forbrugerens/forbrugernes navn,",
    "withdrawal.form.address": "Forbrugerens/forbrugernes adresse,",
    "withdrawal.form.signature": "Forbrugerens/forbrugernes underskrift (kun hvis formularen indgives på papir),",
    "withdrawal.form.date": "Dato.",
    "withdrawal.form.note": "(*) Det ikke relevante overstreges.",

    "h.imprint.legal_name": "Virksomhedens navn",
    "imprint.legal_name": "{name} (driver {store}).",
    "h.imprint.org_number": "Organisationsnummer",
    "imprint.org_number": "{org}.",
    "h.imprint.vat_number": "Moms",
    "imprint.vat.yes": "Momsnummer: {vat}.",
    "imprint.vat.no": "Virksomheden er ikke momsregistreret.",
    "h.imprint.address": "Adresse",
    "imprint.address": "{address}.",
    "h.imprint.email": "E-mail",
    "imprint.email": "{email}.",
    "h.imprint.phone": "Telefon",
    "imprint.phone": "{phone}.",
    "h.imprint.register": "Register",
    "imprint.register": "{check}",
    "h.imprint.supervisory_authority": "Tilsynsmyndighed",
    "imprint.supervisory": "{check}",
  },
};
