/**
 * Legal starter texts in English (wave 1, 1e). HAND-WRITTEN, never machine-translated, and NOT legal advice: a starting
 * point made from the store's own details that a person must read, correct and complete before use. Every sentence here
 * needs human legal review (docs/wave-1-trust.md section 8). `{name}` is where a store's own fact goes; `[[Add: …]]` and
 * `[[Check: …]]` are placeholders the store must deal with. The shape of each page is in `../legal-starters.ts`.
 */
import type { StarterText } from "../legal-starters";

export const EN: StarterText = {
  language: "en",
  locale: "en-GB",
  m: {
    // The notice every starter opens with, and the extra sentence for a store whose language is not one of the four.
    notice:
      "DRAFT: needs legal review before use. Kaizen Store made this text from your store's details as a starting point. It is not legal advice and no lawyer has checked it. Read every sentence, fill in the [[bracketed]] parts, and delete this notice when you have.",
    "notice.language": "This text is in English because it is not available in your store's language: have it translated and reviewed by a person before use.",
    "ph.add": "Add",
    "ph.check": "Check",

    // What a placeholder asks for.
    "label.storeName": "store name",
    "label.legalName": "legal name of the business",
    "label.orgNumber": "organisation number",
    "label.vatNumber": "VAT number",
    "label.address": "postal address",
    "label.email": "contact email",
    "label.phone": "phone number",
    "label.country": "country",
    "label.markets": "countries you sell to",
    "label.currency": "currency",
    "label.shippingPrice": "shipping price",
    "label.carriers": "carriers",
    "label.contractFormation": "when the contract is made: when the order is placed, or when you confirm it",
    "label.deliveryTime": "delivery time",
    "label.guaranteePeriod": "guarantee period",
    "label.complaintBody": "the consumer complaint body in your country",
    "label.legalReferences": "the consumer laws that apply in your country, and which court decides disputes",
    "label.transfers": "where each recipient processes data, and what safeguards apply when data leaves the EU/EEA",
    "label.retentionPeriod": "how long order and accounting records are kept, in years",
    "label.dataAuthority": "the data protection authority in your country, for example Datatilsynet in Norway, IMY in Sweden or Datatilsynet in Denmark",
    "label.aiProvider": "the AI provider the chat assistant uses",
    "label.returnInstructions": "how to return goods: where to send them and how to pack them",
    "label.returnAddress": "return address",
    "label.outsideEu": "whether you deliver outside the EU, and who pays customs, duties and import VAT",
    "label.damagedDays": "within how many days a shopper must report damaged goods",
    "label.exclusionsFit": "which of these exclusions apply to what you sell: delete the rest",
    "label.tradeRegister": "trade register and registration number, if the business is entered in one",
    "label.supervisoryAuthority": "the supervisory authority, if the business needs a licence or is supervised",

    // Titles and addresses of the pages.
    "title.terms": "Terms of sale",
    "title.privacy": "Privacy statement",
    "title.returns_policy": "Returns policy",
    "title.shipping_policy": "Shipping policy",
    "title.withdrawal_info": "Withdrawal information",
    "title.imprint": "Imprint",
    "slug.terms": "terms-of-sale",
    "slug.privacy": "privacy-statement",
    "slug.returns_policy": "returns-policy",
    "slug.shipping_policy": "shipping-policy",
    "slug.withdrawal_info": "withdrawal-information",
    "slug.imprint": "imprint",

    // Shared lines.
    "vat.yes": "VAT number: {vat}.",
    "vat.no": "The business is not registered for VAT.",
    "rate.plain": "{country}: {rate}.",
    "rate.free": "{country}: {rate}, and free for orders over {amount}.",
    "rate.zero": "{country}: free.",
    "rate.none": "{country}: {check}",
    "carriers.some": "We send goods with {carriers}.",
    "carriers.none": "The carriers we use: {check}",
    "excl.custom_made": "goods made to your specifications or clearly personalised",
    "excl.perishable": "goods that spoil quickly or whose shelf life expires quickly",
    "excl.sealed_hygiene": "sealed goods that are not suitable for return for health or hygiene reasons, if you have broken the seal",
    "excl.sealed_media": "sealed audio or video recordings and software, if you have broken the seal",
    "excl.mixed": "goods that, after delivery, are by their nature inseparably mixed with other items",
    "excl.price_fluctuation": "goods whose price depends on movements in the financial market that we cannot control",
    "excl.alcohol": "alcoholic drinks whose price was agreed when the order was made, but whose delivery can only take place after 30 days",
    "excl.periodicals": "newspapers, periodicals and magazines, except subscriptions to them",
    "excl.digital": "digital content that is not on a physical medium, once delivery has begun with your prior consent",
    "excl.dated_service": "accommodation other than for residential purposes, transport of goods, car rental, catering or leisure activities, if the contract sets a specific date or period for the service",
    "excl.service_performed": "services that have been fully performed, if the performance began with your prior express consent and you acknowledged that you lose the right of withdrawal once the service is fully performed",
    "excl.check": "{check}",

    // Terms of sale.
    "h.terms.seller": "Who we are",
    "terms.seller.1": "These terms apply to purchases from {store}, which is run by {name}, organisation number {org}.",
    "terms.seller.2": "Address: {address}. Email: {email}. Phone: {phone}.",
    "h.terms.products_prices": "Goods and prices",
    "terms.products.1": "The main characteristics of each product are described on its product page. Read them before you order.",
    "terms.products.2": "Prices are shown in {currencies}, for the country you shop in. For consumers the prices include VAT.",
    "h.terms.vat_shipping_costs": "VAT and delivery costs",
    "terms.costs.1": "The total price, with VAT and delivery costs, is shown before you place your order. Delivery costs for each country:",
    "terms.costs.none": "Delivery costs: {check}",
    "h.terms.order_contract": "Placing an order",
    "terms.order.1": "When you press the button to order you place a binding order and agree to pay.",
    "terms.order.2": "We confirm your order by email. {check}",
    "terms.order.3": "The version of these terms that applied when you ordered is stored with your order, so that we can show it to you later.",
    "h.terms.payment": "Payment",
    "terms.payment.1": "Payment is made through our payment provider, Stripe, which handles your card or other payment details. We never see your full card number. The payment methods on offer are shown at checkout.",
    "h.terms.delivery": "Delivery",
    "terms.delivery.1": "We deliver to: {markets}.",
    "terms.delivery.2": "Delivery time: {check}",
    "h.terms.withdrawal": "Right of withdrawal",
    "terms.withdrawal.1": "If you are a consumer you have a right to withdraw from the purchase within 14 days of the day you receive the goods, without giving a reason, apart from the exceptions listed in the withdrawal information.",
    "terms.withdrawal.services": "For services, such as a booking, the 14 days run from the day the contract is made.",
    "terms.withdrawal.regular": "For a subscription box (regular delivery of goods) the 14 days run from the day you receive the first delivery.",
    "terms.withdrawal.link": "Read the withdrawal information and [withdraw online]({href}).",
    "terms.withdrawal.nolink": "Read the withdrawal information on this site for how to use the right.",
    "h.terms.returns_link": "Returns",
    "terms.returns.1": "You can return goods within {days} days of receiving them. See the returns policy for how.",
    "terms.returns.shopper": "If you return goods you pay the direct cost of sending them back, unless we say otherwise.",
    "terms.returns.store": "We pay the cost of sending returned goods back to us.",
    "h.terms.conformity": "Faulty goods",
    "terms.conformity.1": "Goods must be as agreed. If they are not, you have the rights that the legal guarantee in your country gives you. These rights are in addition to anything we offer.",
    "terms.conformity.2": "Guarantee period: {check}",
    "h.terms.complaints": "Complaints",
    "terms.complaints.1": "If something is wrong, write to us at {email} as soon as you notice it.",
    "terms.complaints.2": "{check}",
    "h.terms.disputes": "If we cannot agree",
    "terms.disputes.1": "If we cannot settle a complaint together, you can turn to {check}",
    "h.terms.privacy_link": "Personal data",
    "terms.privacy.1": "How we handle your personal data is described in our privacy statement.",
    "h.terms.bookings_subscriptions": "Bookings and subscription boxes",
    "terms.bookings.1": "Appointments, stays and rentals are booked for a set time. You can cancel or move a booking until the time limit shown when you book.",
    "terms.bookings.2": "A subscription box is delivered on the days shown and continues until you stop it. You can change, pause or end it until the cutoff shown before each delivery.",
    "h.terms.businesses": "Purchases by businesses",
    "terms.business.1": "These terms also apply when a business buys from us. Businesses see prices without VAT, but VAT is added to the order where it applies.",
    "terms.business.returns": "The statutory right of withdrawal is for consumers. For businesses we offer return of goods as set out in the returns policy.",
    "terms.business.noreturns": "The statutory right of withdrawal is for consumers and does not apply to purchases by businesses.",
    "h.terms.law_and_changes": "Law and changes",
    "terms.law.1": "These terms are governed by the law of {country}.",
    "terms.law.2": "{check}",
    "terms.law.3": "We may change these terms. The version that applied when you placed your order is the one that applies to that order.",

    // Privacy statement.
    "h.privacy.controller": "Who is responsible",
    "privacy.controller.1": "{name}, organisation number {org}, address {address}, runs {store} and is the controller of the personal data described here.",
    "privacy.controller.2": "The store runs on the Kaizen Store platform. The platform processes personal data on our behalf, as our processor.",
    "h.privacy.contact": "Contact",
    "privacy.contact.1": "Questions about your personal data: {email}. Phone: {phone}.",
    "h.privacy.purposes_basis": "What we use your data for",
    "privacy.purposes.1": "We use personal data for these purposes, each on the legal basis shown:",
    "privacy.purpose.orders": "to take, pay for, deliver and follow up your orders, and to confirm and send you what you have bought (performance of the contract)",
    "privacy.purpose.accounting": "to keep the accounts and records the law requires (legal obligation)",
    "privacy.purpose.service": "to answer your questions and complaints (performance of the contract, and our legitimate interest in giving good service)",
    "privacy.purpose.security": "to keep the store secure and prevent fraud and misuse (our legitimate interest)",
    "privacy.purpose.marketing": "to send you marketing by email, only if you have agreed to it (consent)",
    "privacy.purpose.visits": "to count visits to the store without cookies, to see how it is used; we keep no IP address and no user agent (our legitimate interest)",
    "h.privacy.recipients": "Who receives your data",
    "privacy.recipients.1": "We share personal data only with those who need it:",
    "privacy.recipient.platform": "the Kaizen Store platform, which runs the store and processes data on our behalf",
    "privacy.recipient.stripe": "Stripe, our payment provider, which handles payments",
    "privacy.recipient.email": "the email service the platform uses to send order confirmations and other messages to you",
    "privacy.recipient.carriers": "carriers that deliver your goods: {carriers}",
    "privacy.recipient.carriers.none": "carriers that deliver your goods: {check}",
    "privacy.recipient.tool": "{tool}, which the store loads only if you accept the matching cookies",
    "privacy.recipient.authorities": "public authorities, where the law requires us to share information",
    "h.privacy.transfers": "Transfers outside the EU/EEA",
    "privacy.transfers.1": "The platform stores the store's data in the EU. Some of the recipients above may process data elsewhere.",
    "privacy.transfers.2": "{check}",
    "h.privacy.retention": "How long we keep your data",
    "privacy.retention.1": "Order and accounting records are kept for as long as the law requires: {check}",
    "privacy.retention.2": "Other data is kept only as long as we need it for the purpose it was collected for. A customer account is kept until you delete it.",
    "h.privacy.rights": "Your rights",
    "privacy.rights.1": "You have the right to:",
    "privacy.right.access": "ask for access to the personal data we hold about you",
    "privacy.right.rectify": "have wrong data corrected",
    "privacy.right.erase": "have your data erased, where the law allows (records we must keep by law cannot be erased until the period ends)",
    "privacy.right.restrict": "have the use of your data restricted",
    "privacy.right.portability": "receive your data in a common format and have it moved to another service",
    "privacy.right.object": "object to processing that rests on our legitimate interest",
    "h.privacy.consent_withdrawal": "Withdrawing consent",
    "privacy.consent.1": "Where we use your data because you agreed, you can withdraw your consent at any time. This does not affect what we did before you withdrew it.",
    "h.privacy.complaint_authority": "Complaints to the authority",
    "privacy.complaint.1": "You can complain about how we handle your personal data to the data protection authority: {check}",
    "h.privacy.obligation_to_provide": "Do you have to give us your data?",
    "privacy.obligation.1": "You must give us the details we need to make and deliver your order, such as your name, address and email. Without them we cannot complete the purchase. Anything else is optional.",
    "h.privacy.automated_decisions": "Automated decisions",
    "privacy.automated.1": "We do not make decisions about you that are based only on automated processing and that have legal or similarly significant effects on you.",
    "privacy.automated.chat": "The store has a chat assistant that uses artificial intelligence to answer questions from the store's own information. What you write to it is sent to the AI provider the store uses ({check}). Do not write sensitive personal data to it.",
    "h.privacy.cookies_link": "Cookies",
    "privacy.cookies.link": "The cookies and similar tools the store uses are listed on the [cookies page]({href}).",
    "privacy.cookies.nolink": "The cookies and similar tools the store uses are listed on its cookies page.",

    // Returns policy.
    "h.returns_policy.window": "How long you have",
    "returns.window.1": "You can return goods within {days} days of the day you receive them.",
    "returns.window.extended": "Of these, 14 days are your statutory right of withdrawal as a consumer. The rest, up to {days} days, is our own longer return window, which we offer in addition.",
    "h.returns_policy.how_to": "How to return goods",
    "returns.how.1": "Tell us first that you want to return goods. Then send them back as described below.",
    "returns.how.instructions": "{instructions}",
    "returns.how.noinstructions": "{check}",
    "h.returns_policy.who_pays": "Who pays for the return",
    "returns.pays.shopper": "You pay the direct cost of sending the goods back, unless the goods were faulty or not as agreed.",
    "returns.pays.store": "We pay the cost of sending the goods back.",
    "h.returns_policy.refund_timing": "When you get your money back",
    "returns.refund.received": "We refund what you paid, including standard delivery, no later than 14 days after we learn of your decision. We may wait until we have the goods back, or until you show that you have sent them, whichever is first.",
    "returns.refund.request": "We refund what you paid, including standard delivery, no later than 14 days after we learn of your decision.",
    "h.returns_policy.excluded_goods": "Goods that cannot be returned",
    "returns.excluded.1": "The statutory right of withdrawal does not apply to:",
    "returns.excluded.accept": "We still take back some of these goods inside our own return window, if they are in the condition we ask for.",
    "returns.excluded.refuse": "We do not take back these goods.",
    "h.returns_policy.return_address": "Where to send returns",
    "returns.address.1": "Send returns to: {address}.",
    "h.returns_policy.withdrawal_link": "Withdrawing from a purchase",
    "returns.withdrawal.link": "To withdraw from a purchase as a consumer, [use the withdrawal function]({href}) or read the withdrawal information.",
    "returns.withdrawal.nolink": "To withdraw from a purchase as a consumer, read the withdrawal information on this site.",
    "h.returns_policy.businesses": "Purchases by businesses",
    "returns.business.1": "The statutory right of withdrawal is for consumers.",
    "returns.business.voluntary": "Businesses can return goods in the same way and within the same time as other customers, as a service from us, not as a legal right.",
    "returns.business.none": "It does not apply to purchases by businesses, and we do not take goods back from businesses unless we agree otherwise.",

    // Shipping policy.
    "h.shipping_policy.markets": "Where we deliver",
    "shipping.markets.1": "We deliver to: {markets}.",
    "h.shipping_policy.rates": "What delivery costs",
    "shipping.rates.1": "Delivery costs, with VAT, for each country:",
    "shipping.rates.none": "Delivery costs: {check}",
    "h.shipping_policy.carriers": "Carriers",
    "h.shipping_policy.delivery_time": "How long it takes",
    "shipping.time.1": "Delivery time: {check}",
    "h.shipping_policy.tracking": "Tracking",
    "shipping.tracking.1": "When your order is sent you get an email. Where the carrier offers it, the email has a tracking link.",
    "h.shipping_policy.outside_eu": "Outside the EU",
    "shipping.outside.1": "{check}",
    "h.shipping_policy.damaged_goods": "Damaged goods",
    "shipping.damaged.1": "If goods arrive damaged, tell us {check}",
    "h.shipping_policy.contact": "Questions",
    "shipping.contact.1": "Questions about your delivery: {email}.",

    // Withdrawal information.
    "h.withdrawal_info.right": "Right of withdrawal",
    "withdrawal.right.1": "If you are a consumer you have the right to withdraw from this contract within 14 days without giving any reason.",
    "withdrawal.right.2": "The withdrawal period expires 14 days after the day on which you, or a third party other than the carrier and indicated by you, acquire physical possession of the goods. If you order several goods in one order that are delivered separately, it expires 14 days after the day you receive the last of them.",
    "withdrawal.right.services": "For a service contract, such as a booking, the withdrawal period expires 14 days after the day the contract is made.",
    "withdrawal.right.regular": "For a contract for the regular delivery of goods over a set period, such as a subscription box, the withdrawal period expires 14 days after the day you receive the first delivery.",
    "h.withdrawal_info.how": "How to withdraw",
    "withdrawal.how.1": "To exercise the right, you must inform {name}, {address}, {email}, of your decision to withdraw by a clear statement, for example by a letter sent by post or by email.",
    "withdrawal.how.online": "You can also [withdraw online]({href}) on this site.",
    "withdrawal.how.noonline": "You can also use the withdrawal function on this site.",
    "withdrawal.how.2": "You can use the model withdrawal form below, but you do not have to. To meet the deadline it is enough that you send your notice before the withdrawal period has expired.",
    "h.withdrawal_info.effects": "What happens when you withdraw",
    "withdrawal.effects.1": "If you withdraw from this contract, we will reimburse all payments we have received from you, including the costs of standard delivery, without undue delay and no later than 14 days after the day we are informed of your decision.",
    "withdrawal.effects.2": "We may withhold the reimbursement until we have received the goods back or you have supplied evidence of having sent them back, whichever is the earliest. We will use the same means of payment as you used for the order, unless you agree otherwise.",
    "withdrawal.effects.3": "You must send back the goods, or hand them over to us, without undue delay and no later than 14 days after the day you informed us of your withdrawal.",
    "withdrawal.effects.pays.shopper": "You pay the direct cost of returning the goods.",
    "withdrawal.effects.pays.store": "We pay the cost of returning the goods.",
    "withdrawal.effects.4": "You are only liable for any diminished value of the goods resulting from handling other than what is necessary to establish their nature, characteristics and functioning.",
    "withdrawal.effects.services": "If you asked for a service to begin during the withdrawal period, you must pay us an amount in proportion to what has been provided until you told us you withdraw, compared with the full coverage of the contract.",
    "h.withdrawal_info.exclusions": "When there is no right of withdrawal",
    "withdrawal.excl.1": "There is no right of withdrawal for:",
    "h.withdrawal_info.model_form": "Model withdrawal form",
    "withdrawal.form.1": "Complete and return this form only if you wish to withdraw from the contract.",
    "withdrawal.form.to": "To {name}, {address}, {email}:",
    "withdrawal.form.notice": "I/We (*) hereby give notice that I/We (*) withdraw from my/our (*) contract of sale of the following goods (*) / for the provision of the following service (*),",
    "withdrawal.form.ordered": "Ordered on (*) / received on (*),",
    "withdrawal.form.consumer": "Name of consumer(s),",
    "withdrawal.form.address": "Address of consumer(s),",
    "withdrawal.form.signature": "Signature of consumer(s) (only if this form is notified on paper),",
    "withdrawal.form.date": "Date.",
    "withdrawal.form.note": "(*) Delete as appropriate.",

    // Imprint.
    "h.imprint.legal_name": "Business name",
    "imprint.legal_name": "{name} (trading as {store}).",
    "h.imprint.org_number": "Organisation number",
    "imprint.org_number": "{org}.",
    "h.imprint.vat_number": "VAT",
    "imprint.vat.yes": "VAT number: {vat}.",
    "imprint.vat.no": "The business is not registered for VAT.",
    "h.imprint.address": "Address",
    "imprint.address": "{address}.",
    "h.imprint.email": "Email",
    "imprint.email": "{email}.",
    "h.imprint.phone": "Phone",
    "imprint.phone": "{phone}.",
    "h.imprint.register": "Register",
    "imprint.register": "{check}",
    "h.imprint.supervisory_authority": "Supervisory authority",
    "imprint.supervisory": "{check}",
  },
};
