/**
 * Juridiske startertekster på norsk bokmål (bølge 1, 1e). SKREVET FOR HÅND, aldri maskinoversatt, og IKKE juridisk
 * rådgivning: et utgangspunkt laget av butikkens egne opplysninger som et menneske må lese, rette og fullføre før bruk.
 * Hver setning her må gjennomgås juridisk av en person (docs/wave-1-trust.md avsnitt 8). `{name}` er stedet der
 * butikkens egne opplysninger settes inn; `[[Legg til: …]]` og `[[Kontroller: …]]` er plassholdere butikken må ta stilling
 * til. Formen på hver side er i `../legal-starters.ts`. Modellskjemaet for angrerett følger direktivets vedlegg I(B) i
 * innhold, men er ikke kopiert fra den offisielle norske teksten: kontroller mot den.
 */
import type { StarterText } from "../legal-starters";

export const NB: StarterText = {
  language: "nb",
  locale: "nb-NO",
  m: {
    notice:
      "UTKAST: må gjennomgås juridisk før bruk. Kaizen Store har laget denne teksten av butikkens opplysninger som et utgangspunkt. Den er ikke juridisk rådgivning, og ingen jurist har kontrollert den. Les hver setning, fyll inn delene i [[klammer]], og slett denne merknaden når du har gjort det.",
    "notice.language": "Denne teksten er på norsk bokmål fordi den ikke finnes på butikkens språk: la en person oversette og gjennomgå den før bruk.",
    "ph.add": "Legg til",
    "ph.check": "Kontroller",

    "label.storeName": "butikkens navn",
    "label.legalName": "virksomhetens juridiske navn",
    "label.orgNumber": "organisasjonsnummer",
    "label.vatNumber": "MVA-nummer",
    "label.address": "postadresse",
    "label.email": "e-postadresse for kontakt",
    "label.phone": "telefonnummer",
    "label.country": "land",
    "label.markets": "landene dere selger til",
    "label.currency": "valuta",
    "label.shippingPrice": "fraktpris",
    "label.carriers": "fraktselskaper",
    "label.contractFormation": "når avtalen inngås: når bestillingen sendes, eller når dere bekrefter den",
    "label.deliveryTime": "leveringstid",
    "label.guaranteePeriod": "reklamasjonsfrist",
    "label.complaintBody": "klageorganet for forbrukere i landet ditt",
    "label.legalReferences": "forbrukerlovene som gjelder i landet ditt, og hvilken domstol som avgjør tvister",
    "label.transfers": "hvor hver mottaker behandler opplysningene, og hvilke garantier som gjelder når opplysninger forlater EU/EØS",
    "label.retentionPeriod": "hvor lenge ordre- og regnskapsopplysninger oppbevares, i år",
    "label.dataAuthority": "personvernmyndigheten i landet ditt, for eksempel Datatilsynet i Norge, IMY i Sverige eller Datatilsynet i Danmark",
    "label.aiProvider": "AI-leverandøren chatassistenten bruker",
    "label.returnInstructions": "hvordan varer returneres: hvor de sendes og hvordan de pakkes",
    "label.returnAddress": "returadresse",
    "label.outsideEu": "om dere leverer utenfor EU, og hvem som betaler toll, avgifter og innførselsmerverdiavgift",
    "label.damagedDays": "innen hvor mange dager kunden må melde fra om skadde varer",
    "label.exclusionsFit": "hvilke av unntakene her som gjelder det dere selger: slett resten",
    "label.tradeRegister": "foretaksregister og registreringsnummer, hvis virksomheten er innført i et",
    "label.supervisoryAuthority": "tilsynsmyndigheten, hvis virksomheten trenger tillatelse eller er under tilsyn",

    "title.terms": "Kjøpsvilkår",
    "title.privacy": "Personvernerklæring",
    "title.returns_policy": "Returpolitikk",
    "title.shipping_policy": "Frakt og levering",
    "title.withdrawal_info": "Informasjon om angrerett",
    "title.imprint": "Om virksomheten",
    "slug.terms": "kjopsvilkar",
    "slug.privacy": "personvernerklaering",
    "slug.returns_policy": "returpolitikk",
    "slug.shipping_policy": "frakt-og-levering",
    "slug.withdrawal_info": "angrerett",
    "slug.imprint": "om-virksomheten",

    "vat.yes": "MVA-nummer: {vat}.",
    "vat.no": "Virksomheten er ikke registrert for merverdiavgift.",
    "rate.plain": "{country}: {rate}.",
    "rate.free": "{country}: {rate}, og gratis for bestillinger over {amount}.",
    "rate.zero": "{country}: gratis.",
    "rate.none": "{country}: {check}",
    "carriers.some": "Vi sender varene med {carriers}.",
    "carriers.none": "Fraktselskapene vi bruker: {check}",
    "excl.custom_made": "varer som er laget etter dine ønsker eller tydelig tilpasset deg personlig",
    "excl.perishable": "varer som raskt blir ødelagt eller får utløpt holdbarhet",
    "excl.sealed_hygiene": "forseglede varer som ikke er egnet til retur av helse- eller hygienehensyn, hvis forseglingen er brutt",
    "excl.sealed_media": "forseglede lyd- eller bildeopptak og programvare, hvis forseglingen er brutt",
    "excl.mixed": "varer som etter levering, på grunn av sin art, er uatskillelig blandet med andre varer",
    "excl.price_fluctuation": "varer hvis pris avhenger av svingninger i finansmarkedet som vi ikke kan påvirke",
    "excl.alcohol": "alkoholholdige drikkevarer der prisen ble avtalt ved bestillingen, men som først kan leveres etter 30 dager",
    "excl.periodicals": "aviser, tidsskrifter og blader, med unntak av abonnement på dem",
    "excl.digital": "digitalt innhold som ikke leveres på et fysisk medium, når leveringen er påbegynt med ditt forutgående samtykke",
    "excl.dated_service": "overnatting som ikke er til boligformål, transport av varer, utleie av bil, servering eller fritidsaktiviteter, hvis avtalen angir et bestemt tidspunkt eller en bestemt periode for tjenesten",
    "excl.service_performed": "tjenester som er fullt utført, hvis utførelsen startet med ditt uttrykkelige forutgående samtykke og du bekreftet at du mister angreretten når tjenesten er fullt utført",
    "excl.check": "{check}",

    "h.terms.seller": "Hvem vi er",
    "terms.seller.1": "Disse vilkårene gjelder kjøp fra {store}, som drives av {name}, organisasjonsnummer {org}.",
    "terms.seller.2": "Adresse: {address}. E-post: {email}. Telefon: {phone}.",
    "h.terms.products_prices": "Varer og priser",
    "terms.products.1": "Hovedegenskapene til hvert produkt er beskrevet på produktsiden. Les dem før du bestiller.",
    "terms.products.2": "Prisene vises i {currencies}, for landet du handler i. For forbrukere er prisene oppgitt med merverdiavgift.",
    "h.terms.vat_shipping_costs": "Merverdiavgift og leveringskostnader",
    "terms.costs.1": "Totalprisen, med merverdiavgift og leveringskostnader, vises før du sender bestillingen. Leveringskostnader for hvert land:",
    "terms.costs.none": "Leveringskostnader: {check}",
    "h.terms.order_contract": "Når du bestiller",
    "terms.order.1": "Når du trykker på knappen for å bestille, sender du en bindende bestilling og forplikter deg til å betale.",
    "terms.order.2": "Vi bekrefter bestillingen din på e-post. {check}",
    "terms.order.3": "Den versjonen av disse vilkårene som gjaldt da du bestilte, lagres sammen med bestillingen din, slik at vi kan vise den til deg senere.",
    "h.terms.payment": "Betaling",
    "terms.payment.1": "Betalingen går gjennom betalingsleverandøren vår, Stripe, som håndterer kortopplysningene eller andre betalingsopplysninger dine. Vi ser aldri hele kortnummeret ditt. Betalingsmåtene som tilbys, vises i kassen.",
    "h.terms.delivery": "Levering",
    "terms.delivery.1": "Vi leverer til: {markets}.",
    "terms.delivery.2": "Leveringstid: {check}",
    "h.terms.withdrawal": "Angrerett",
    "terms.withdrawal.1": "Er du forbruker, har du rett til å angre kjøpet innen 14 dager fra dagen du mottar varene, uten å oppgi grunn, med unntak av det som er nevnt i informasjonen om angrerett.",
    "terms.withdrawal.services": "For tjenester, for eksempel en booking, løper de 14 dagene fra den dagen avtalen ble inngått.",
    "terms.withdrawal.regular": "For en abonnementsboks (regelmessig levering av varer) løper de 14 dagene fra den dagen du mottar den første leveringen.",
    "terms.withdrawal.link": "Les informasjonen om angrerett og [bruk angrefunksjonen]({href}).",
    "terms.withdrawal.nolink": "Les informasjonen om angrerett på dette nettstedet for å se hvordan du bruker retten.",
    "h.terms.returns_link": "Retur",
    "terms.returns.1": "Du kan returnere varer innen {days} dager etter at du har mottatt dem. Se returpolitikken for hvordan.",
    "terms.returns.shopper": "Når du returnerer varer, betaler du de direkte kostnadene ved å sende dem tilbake, med mindre vi sier noe annet.",
    "terms.returns.store": "Vi betaler kostnaden ved å sende returnerte varer tilbake til oss.",
    "h.terms.conformity": "Mangler ved varen",
    "terms.conformity.1": "Varene skal være som avtalt. Er de ikke det, har du de rettighetene som den lovbestemte garantien i ditt land gir deg. Rettighetene kommer i tillegg til det vi selv tilbyr.",
    "terms.conformity.2": "Reklamasjonsfrist: {check}",
    "h.terms.complaints": "Reklamasjon",
    "terms.complaints.1": "Er noe galt, skriv til oss på {email} så snart du oppdager det.",
    "terms.complaints.2": "{check}",
    "h.terms.disputes": "Hvis vi ikke blir enige",
    "terms.disputes.1": "Hvis vi ikke blir enige om en klage, kan du henvende deg til {check}",
    "h.terms.privacy_link": "Personopplysninger",
    "terms.privacy.1": "Hvordan vi behandler personopplysningene dine, er beskrevet i personvernerklæringen vår.",
    "h.terms.bookings_subscriptions": "Bookinger og abonnementsbokser",
    "terms.bookings.1": "Avtaler, opphold og utleie bestilles for et bestemt tidspunkt. Du kan avbestille eller flytte en booking frem til fristen som vises når du bestiller.",
    "terms.bookings.2": "En abonnementsboks leveres på dagene som vises, og fortsetter til du stopper den. Du kan endre, sette på pause eller avslutte den frem til fristen som vises før hver levering.",
    "h.terms.businesses": "Kjøp fra bedrifter",
    "terms.business.1": "Disse vilkårene gjelder også når en bedrift kjøper av oss. Bedrifter ser priser uten merverdiavgift, men merverdiavgift legges til bestillingen der den gjelder.",
    "terms.business.returns": "Den lovbestemte angreretten gjelder forbrukere. For bedrifter tilbyr vi retur av varer slik det står i returpolitikken.",
    "terms.business.noreturns": "Den lovbestemte angreretten gjelder forbrukere og gjelder ikke når en bedrift kjøper.",
    "h.terms.law_and_changes": "Lovvalg og endringer",
    "terms.law.1": "Disse vilkårene er underlagt lovene i {country}.",
    "terms.law.2": "{check}",
    "terms.law.3": "Vi kan endre disse vilkårene. Den versjonen som gjaldt da du la inn bestillingen, er den som gjelder for den bestillingen.",

    "h.privacy.controller": "Hvem som er ansvarlig",
    "privacy.controller.1": "{name}, organisasjonsnummer {org}, adresse {address}, driver {store} og er behandlingsansvarlig for personopplysningene som er beskrevet her.",
    "privacy.controller.2": "Butikken kjører på plattformen Kaizen Store. Plattformen behandler personopplysninger på våre vegne, som vår databehandler.",
    "h.privacy.contact": "Kontakt",
    "privacy.contact.1": "Spørsmål om personopplysningene dine: {email}. Telefon: {phone}.",
    "h.privacy.purposes_basis": "Hva vi bruker opplysningene til",
    "privacy.purposes.1": "Vi bruker personopplysninger til disse formålene, hvert på det rettslige grunnlaget som er oppgitt:",
    "privacy.purpose.orders": "å ta imot, ta betalt for, levere og følge opp bestillingene dine, og å bekrefte og sende deg det du har kjøpt (oppfyllelse av avtalen)",
    "privacy.purpose.accounting": "å føre regnskapet og oppbevare dokumentasjonen som loven krever (rettslig forpliktelse)",
    "privacy.purpose.service": "å svare på spørsmål og klager fra deg (oppfyllelse av avtalen, og vår berettigede interesse i å gi god service)",
    "privacy.purpose.security": "å holde butikken sikker og forhindre svindel og misbruk (vår berettigede interesse)",
    "privacy.purpose.marketing": "å sende deg markedsføring på e-post, bare hvis du har sagt ja til det (samtykke)",
    "privacy.purpose.visits": "å telle besøk i butikken uten informasjonskapsler, for å se hvordan den brukes; vi lagrer ingen IP-adresse og ingen nettleseridentifikator (vår berettigede interesse)",
    "h.privacy.recipients": "Hvem som får opplysningene",
    "privacy.recipients.1": "Vi deler personopplysninger bare med dem som trenger dem:",
    "privacy.recipient.platform": "plattformen Kaizen Store, som driver butikken og behandler opplysninger på våre vegne",
    "privacy.recipient.stripe": "Stripe, betalingsleverandøren vår, som håndterer betalinger",
    "privacy.recipient.email": "e-posttjenesten plattformen bruker til å sende ordrebekreftelser og andre meldinger til deg",
    "privacy.recipient.carriers": "fraktselskaper som leverer varene dine: {carriers}",
    "privacy.recipient.carriers.none": "fraktselskaper som leverer varene dine: {check}",
    "privacy.recipient.tool": "{tool}, som butikken bare laster hvis du godtar de tilhørende informasjonskapslene",
    "privacy.recipient.authorities": "offentlige myndigheter, når loven krever at vi deler opplysninger",
    "h.privacy.transfers": "Overføring utenfor EU/EØS",
    "privacy.transfers.1": "Plattformen lagrer butikkens data i EU. Noen av mottakerne ovenfor kan behandle opplysninger andre steder.",
    "privacy.transfers.2": "{check}",
    "h.privacy.retention": "Hvor lenge vi oppbevarer opplysningene",
    "privacy.retention.1": "Ordre- og regnskapsopplysninger oppbevares så lenge loven krever: {check}",
    "privacy.retention.2": "Andre opplysninger oppbevares bare så lenge vi trenger dem til formålet de ble samlet inn for. En kundekonto oppbevares til du sletter den.",
    "h.privacy.rights": "Rettighetene dine",
    "privacy.rights.1": "Du har rett til å:",
    "privacy.right.access": "be om innsyn i personopplysningene vi har om deg",
    "privacy.right.rectify": "få uriktige opplysninger rettet",
    "privacy.right.erase": "få opplysningene dine slettet, der loven tillater det (dokumentasjon vi må oppbevare etter loven, kan ikke slettes før perioden er over)",
    "privacy.right.restrict": "kreve at bruken av opplysningene dine begrenses",
    "privacy.right.portability": "få opplysningene dine i et vanlig format og få dem overført til en annen tjeneste",
    "privacy.right.object": "protestere mot behandling som bygger på vår berettigede interesse",
    "h.privacy.consent_withdrawal": "Trekke tilbake samtykke",
    "privacy.consent.1": "Der vi bruker opplysningene dine fordi du har samtykket, kan du når som helst trekke samtykket tilbake. Det påvirker ikke det vi gjorde før du trakk det tilbake.",
    "h.privacy.complaint_authority": "Klage til myndigheten",
    "privacy.complaint.1": "Du kan klage på hvordan vi behandler personopplysningene dine til personvernmyndigheten: {check}",
    "h.privacy.obligation_to_provide": "Må du gi oss opplysningene?",
    "privacy.obligation.1": "Du må gi oss opplysningene vi trenger for å inngå og levere bestillingen din, som navn, adresse og e-post. Uten dem kan vi ikke gjennomføre kjøpet. Alt annet er frivillig.",
    "h.privacy.automated_decisions": "Automatiserte avgjørelser",
    "privacy.automated.1": "Vi tar ikke avgjørelser om deg som utelukkende bygger på automatisert behandling, og som har rettslige eller tilsvarende betydelige følger for deg.",
    "privacy.automated.chat": "Butikken har en chatassistent som bruker kunstig intelligens til å svare på spørsmål ut fra butikkens egen informasjon. Det du skriver til den, sendes til AI-leverandøren butikken bruker ({check}). Ikke skriv sensitive personopplysninger til den.",
    "h.privacy.cookies_link": "Informasjonskapsler",
    "privacy.cookies.link": "Informasjonskapslene og tilsvarende verktøy butikken bruker, er oppført på [siden om informasjonskapsler]({href}).",
    "privacy.cookies.nolink": "Informasjonskapslene og tilsvarende verktøy butikken bruker, er oppført på butikkens side om informasjonskapsler.",

    "h.returns_policy.window": "Hvor lenge du har",
    "returns.window.1": "Du kan returnere varer innen {days} dager fra dagen du mottar dem.",
    "returns.window.extended": "Av disse er 14 dager din lovbestemte angrerett som forbruker. Resten, opp til {days} dager, er vår egen lengre returfrist, som vi tilbyr i tillegg.",
    "h.returns_policy.how_to": "Slik returnerer du",
    "returns.how.1": "Si først fra til oss at du vil returnere varer. Send dem deretter tilbake som beskrevet nedenfor.",
    "returns.how.instructions": "{instructions}",
    "returns.how.noinstructions": "{check}",
    "h.returns_policy.who_pays": "Hvem som betaler for returen",
    "returns.pays.shopper": "Du betaler de direkte kostnadene ved å sende varene tilbake, med mindre varene var mangelfulle eller ikke som avtalt.",
    "returns.pays.store": "Vi betaler kostnaden ved å sende varene tilbake.",
    "h.returns_policy.refund_timing": "Når du får pengene tilbake",
    "returns.refund.received": "Vi refunderer det du har betalt, inkludert standard levering, senest 14 dager etter at vi har fått vite om avgjørelsen din. Vi kan vente til vi har fått varene tilbake, eller til du har vist at du har sendt dem, avhengig av hva som skjer først.",
    "returns.refund.request": "Vi refunderer det du har betalt, inkludert standard levering, senest 14 dager etter at vi har fått vite om avgjørelsen din.",
    "h.returns_policy.excluded_goods": "Varer som ikke kan returneres",
    "returns.excluded.1": "Den lovbestemte angreretten gjelder ikke for:",
    "returns.excluded.accept": "Vi tar likevel tilbake noen av disse varene innenfor vår egen returfrist, hvis de er i den stand vi ber om.",
    "returns.excluded.refuse": "Vi tar ikke tilbake disse varene.",
    "h.returns_policy.return_address": "Hvor returer sendes",
    "returns.address.1": "Send returer til: {address}.",
    "h.returns_policy.withdrawal_link": "Å angre et kjøp",
    "returns.withdrawal.link": "For å angre et kjøp som forbruker, [bruk angrefunksjonen]({href}) eller les informasjonen om angrerett.",
    "returns.withdrawal.nolink": "For å angre et kjøp som forbruker, les informasjonen om angrerett på dette nettstedet.",
    "h.returns_policy.businesses": "Kjøp fra bedrifter",
    "returns.business.1": "Den lovbestemte angreretten gjelder forbrukere.",
    "returns.business.voluntary": "Bedrifter kan returnere varer på samme måte og innen samme frist som andre kunder, som en service fra oss og ikke som en lovfestet rett.",
    "returns.business.none": "Den gjelder ikke når en bedrift kjøper, og vi tar ikke tilbake varer fra bedrifter med mindre vi avtaler noe annet.",

    "h.shipping_policy.markets": "Hvor vi leverer",
    "shipping.markets.1": "Vi leverer til: {markets}.",
    "h.shipping_policy.rates": "Hva levering koster",
    "shipping.rates.1": "Leveringskostnader, med merverdiavgift, for hvert land:",
    "shipping.rates.none": "Leveringskostnader: {check}",
    "h.shipping_policy.carriers": "Fraktselskaper",
    "h.shipping_policy.delivery_time": "Hvor lang tid det tar",
    "shipping.time.1": "Leveringstid: {check}",
    "h.shipping_policy.tracking": "Sporing",
    "shipping.tracking.1": "Når bestillingen din er sendt, får du en e-post. Der fraktselskapet tilbyr det, har e-posten en sporingslenke.",
    "h.shipping_policy.outside_eu": "Utenfor EU",
    "shipping.outside.1": "{check}",
    "h.shipping_policy.damaged_goods": "Skadde varer",
    "shipping.damaged.1": "Hvis varer kommer fram skadet, si fra til oss {check}",
    "h.shipping_policy.contact": "Spørsmål",
    "shipping.contact.1": "Spørsmål om leveringen din: {email}.",

    "h.withdrawal_info.right": "Angrerett",
    "withdrawal.right.1": "Er du forbruker, har du rett til å gå fra denne avtalen innen 14 dager uten å oppgi noen grunn.",
    "withdrawal.right.2": "Angrefristen utløper 14 dager etter den dagen du, eller en tredjepart som du har utpekt og som ikke er transportøren, får varene i fysisk besittelse. Bestiller du flere varer i én bestilling som leveres hver for seg, utløper fristen 14 dager etter den dagen du mottar den siste av dem.",
    "withdrawal.right.services": "For en tjenesteavtale, for eksempel en booking, utløper angrefristen 14 dager etter den dagen avtalen ble inngått.",
    "withdrawal.right.regular": "For en avtale om regelmessig levering av varer over en bestemt periode, for eksempel en abonnementsboks, utløper angrefristen 14 dager etter den dagen du mottar den første leveringen.",
    "h.withdrawal_info.how": "Slik angrer du",
    "withdrawal.how.1": "For å bruke angreretten må du gi {name}, {address}, {email}, beskjed om at du går fra avtalen, i en klar erklæring, for eksempel i et brev sendt med post eller på e-post.",
    "withdrawal.how.online": "Du kan også [angre på nettet]({href}) på dette nettstedet.",
    "withdrawal.how.noonline": "Du kan også bruke angrefunksjonen på dette nettstedet.",
    "withdrawal.how.2": "Du kan bruke modellskjemaet nedenfor, men du må ikke. For å overholde fristen er det nok at du sender beskjeden din før angrefristen er utløpt.",
    "h.withdrawal_info.effects": "Hva som skjer når du angrer",
    "withdrawal.effects.1": "Går du fra avtalen, refunderer vi alle betalinger vi har mottatt fra deg, inkludert kostnadene ved standard levering, uten unødig opphold og senest 14 dager etter den dagen vi får vite om avgjørelsen din.",
    "withdrawal.effects.2": "Vi kan holde tilbake refusjonen til vi har fått varene tilbake, eller til du har vist at du har sendt dem tilbake, avhengig av hva som skjer først. Vi bruker samme betalingsmåte som du brukte ved bestillingen, med mindre du godtar noe annet.",
    "withdrawal.effects.3": "Du må sende varene tilbake eller levere dem til oss uten unødig opphold og senest 14 dager etter den dagen du ga oss beskjed om at du angrer.",
    "withdrawal.effects.pays.shopper": "Du betaler de direkte kostnadene ved å returnere varene.",
    "withdrawal.effects.pays.store": "Vi betaler kostnaden ved å returnere varene.",
    "withdrawal.effects.4": "Du svarer bare for en eventuell redusert verdi på varene som skyldes annen håndtering enn det som er nødvendig for å fastslå varenes art, egenskaper og funksjon.",
    "withdrawal.effects.services": "Har du bedt om at en tjeneste skal starte i angrefristen, må du betale oss et beløp som står i forhold til det som er levert frem til du ga oss beskjed om at du angrer, sammenlignet med hele avtalens omfang.",
    "h.withdrawal_info.exclusions": "Når det ikke er angrerett",
    "withdrawal.excl.1": "Det er ikke angrerett for:",
    "h.withdrawal_info.model_form": "Modellskjema for angrerett",
    "withdrawal.form.1": "Fyll ut og send inn dette skjemaet bare hvis du vil gå fra avtalen.",
    "withdrawal.form.to": "Til {name}, {address}, {email}:",
    "withdrawal.form.notice": "Jeg/vi (*) melder herved at jeg/vi (*) går fra min/vår (*) avtale om kjøp av følgende varer (*) / om levering av følgende tjeneste (*),",
    "withdrawal.form.ordered": "Bestilt den (*) / mottatt den (*),",
    "withdrawal.form.consumer": "Forbrukerens/forbrukernes navn,",
    "withdrawal.form.address": "Forbrukerens/forbrukernes adresse,",
    "withdrawal.form.signature": "Forbrukerens/forbrukernes underskrift (bare hvis skjemaet sendes på papir),",
    "withdrawal.form.date": "Dato.",
    "withdrawal.form.note": "(*) Stryk det som ikke passer.",

    "h.imprint.legal_name": "Virksomhetens navn",
    "imprint.legal_name": "{name} (driver {store}).",
    "h.imprint.org_number": "Organisasjonsnummer",
    "imprint.org_number": "{org}.",
    "h.imprint.vat_number": "Merverdiavgift",
    "imprint.vat.yes": "MVA-nummer: {vat}.",
    "imprint.vat.no": "Virksomheten er ikke registrert for merverdiavgift.",
    "h.imprint.address": "Adresse",
    "imprint.address": "{address}.",
    "h.imprint.email": "E-post",
    "imprint.email": "{email}.",
    "h.imprint.phone": "Telefon",
    "imprint.phone": "{phone}.",
    "h.imprint.register": "Register",
    "imprint.register": "{check}",
    "h.imprint.supervisory_authority": "Tilsynsmyndighet",
    "imprint.supervisory": "{check}",
  },
};
