/**
 * Juridiska startertexter på svenska (våg 1, 1e). SKRIVNA FÖR HAND, aldrig maskinöversatta, och INTE juridisk
 * rådgivning: en utgångspunkt som gjorts av butikens egna uppgifter och som en person måste läsa, rätta och komplettera före
 * användning. Varje mening här måste granskas juridiskt av en person (docs/wave-1-trust.md avsnitt 8). `{name}` är platsen
 * för butikens egna uppgifter; `[[Lägg till: …]]` och `[[Kontrollera: …]]` är platshållare som butiken måste ta ställning
 * till. Sidornas form finns i `../legal-starters.ts`. Modellblanketten för ångerrätt följer direktivets bilaga I(B) till
 * innehållet men är inte kopierad från den officiella svenska texten: kontrollera mot den.
 */
import type { StarterText } from "../legal-starters";

export const SV: StarterText = {
  language: "sv",
  locale: "sv-SE",
  m: {
    notice:
      "UTKAST: måste granskas juridiskt före användning. Kaizen Store har gjort den här texten av butikens uppgifter som en utgångspunkt. Den är inte juridisk rådgivning och ingen jurist har kontrollerat den. Läs varje mening, fyll i delarna inom [[hakparenteser]] och ta bort den här anteckningen när du har gjort det.",
    "notice.language": "Den här texten är på svenska eftersom den inte finns på butikens språk: låt en person översätta och granska den före användning.",
    "ph.add": "Lägg till",
    "ph.check": "Kontrollera",

    "label.storeName": "butikens namn",
    "label.legalName": "verksamhetens juridiska namn",
    "label.orgNumber": "organisationsnummer",
    "label.vatNumber": "momsregistreringsnummer",
    "label.address": "postadress",
    "label.email": "e-postadress för kontakt",
    "label.phone": "telefonnummer",
    "label.country": "land",
    "label.markets": "länderna ni säljer till",
    "label.currency": "valuta",
    "label.shippingPrice": "fraktpris",
    "label.carriers": "fraktbolag",
    "label.contractFormation": "när avtalet ingås: när beställningen läggs, eller när ni bekräftar den",
    "label.deliveryTime": "leveranstid",
    "label.guaranteePeriod": "reklamationstid",
    "label.complaintBody": "konsumenternas tvistlösningsorgan i ditt land",
    "label.legalReferences": "de konsumentlagar som gäller i ditt land, och vilken domstol som avgör tvister",
    "label.transfers": "var varje mottagare behandlar uppgifterna, och vilka skyddsåtgärder som gäller när uppgifter lämnar EU/EES",
    "label.retentionPeriod": "hur länge order- och bokföringsuppgifter sparas, i år",
    "label.dataAuthority": "dataskyddsmyndigheten i ditt land, till exempel Datatilsynet i Norge, IMY i Sverige eller Datatilsynet i Danmark",
    "label.aiProvider": "den AI-leverantör som chattassistenten använder",
    "label.returnInstructions": "hur varor returneras: vart de skickas och hur de packas",
    "label.returnAddress": "returadress",
    "label.outsideEu": "om ni levererar utanför EU, och vem som betalar tull, avgifter och importmoms",
    "label.damagedDays": "inom hur många dagar kunden måste anmäla skadade varor",
    "label.exclusionsFit": "vilka av undantagen här som gäller det ni säljer: ta bort resten",
    "label.tradeRegister": "handelsregister och registreringsnummer, om verksamheten är införd i ett",
    "label.supervisoryAuthority": "tillsynsmyndigheten, om verksamheten behöver tillstånd eller står under tillsyn",

    "title.terms": "Köpvillkor",
    "title.privacy": "Integritetspolicy",
    "title.returns_policy": "Returpolicy",
    "title.shipping_policy": "Frakt och leverans",
    "title.withdrawal_info": "Information om ångerrätt",
    "title.imprint": "Om verksamheten",
    "slug.terms": "kopvillkor",
    "slug.privacy": "integritetspolicy",
    "slug.returns_policy": "returpolicy",
    "slug.shipping_policy": "frakt-och-leverans",
    "slug.withdrawal_info": "angerratt",
    "slug.imprint": "om-verksamheten",

    "vat.yes": "Momsregistreringsnummer: {vat}.",
    "vat.no": "Verksamheten är inte registrerad för moms.",
    "rate.plain": "{country}: {rate}.",
    "rate.free": "{country}: {rate}, och gratis för beställningar över {amount}.",
    "rate.zero": "{country}: gratis.",
    "rate.none": "{country}: {check}",
    "carriers.some": "Vi skickar varorna med {carriers}.",
    "carriers.none": "Fraktbolagen vi använder: {check}",
    "excl.custom_made": "varor som tillverkats enligt dina önskemål eller tydligt anpassats för dig personligen",
    "excl.perishable": "varor som snabbt förstörs eller vars hållbarhet snabbt går ut",
    "excl.sealed_hygiene": "förseglade varor som av hälso- eller hygienskäl inte lämpar sig för retur, om förseglingen har brutits",
    "excl.sealed_media": "förseglade ljud- eller bildupptagningar och programvara, om förseglingen har brutits",
    "excl.mixed": "varor som efter leveransen, på grund av sin art, oåterkalleligen blandats med andra varor",
    "excl.price_fluctuation": "varor vars pris beror på svängningar på finansmarknaden som vi inte kan påverka",
    "excl.alcohol": "alkoholhaltiga drycker vars pris avtalades vid beställningen men som först kan levereras efter 30 dagar",
    "excl.periodicals": "tidningar, tidskrifter och magasin, med undantag för prenumerationer på dem",
    "excl.digital": "digitalt innehåll som inte levereras på ett fysiskt medium, när leveransen har påbörjats med ditt föregående samtycke",
    "excl.dated_service": "inkvartering som inte är för boende, godstransport, biluthyrning, måltider eller fritidsaktiviteter, om avtalet anger en bestämd dag eller period för tjänsten",
    "excl.service_performed": "tjänster som är fullt utförda, om utförandet påbörjades med ditt uttryckliga föregående samtycke och du bekräftade att du förlorar ångerrätten när tjänsten är fullt utförd",
    "excl.check": "{check}",

    "h.terms.seller": "Vilka vi är",
    "terms.seller.1": "De här villkoren gäller köp från {store}, som drivs av {name}, organisationsnummer {org}.",
    "terms.seller.2": "Adress: {address}. E-post: {email}. Telefon: {phone}.",
    "h.terms.products_prices": "Varor och priser",
    "terms.products.1": "De viktigaste egenskaperna hos varje produkt beskrivs på produktsidan. Läs dem innan du beställer.",
    "terms.products.2": "Priserna visas i {currencies}, för det land du handlar i. För konsumenter är priserna angivna inklusive moms.",
    "h.terms.vat_shipping_costs": "Moms och leveranskostnader",
    "terms.costs.1": "Totalpriset, med moms och leveranskostnader, visas innan du lägger beställningen. Leveranskostnader för varje land:",
    "terms.costs.none": "Leveranskostnader: {check}",
    "h.terms.order_contract": "När du beställer",
    "terms.order.1": "När du trycker på knappen för att beställa lägger du en bindande beställning och förbinder dig att betala.",
    "terms.order.2": "Vi bekräftar din beställning med e-post. {check}",
    "terms.order.3": "Den version av de här villkoren som gällde när du beställde sparas tillsammans med din beställning, så att vi kan visa den för dig senare.",
    "h.terms.payment": "Betalning",
    "terms.payment.1": "Betalningen går via vår betaltjänstleverantör Stripe, som hanterar dina kortuppgifter eller andra betalningsuppgifter. Vi ser aldrig hela ditt kortnummer. De betalningssätt som erbjuds visas i kassan.",
    "h.terms.delivery": "Leverans",
    "terms.delivery.1": "Vi levererar till: {markets}.",
    "terms.delivery.2": "Leveranstid: {check}",
    "h.terms.withdrawal": "Ångerrätt",
    "terms.withdrawal.1": "Om du är konsument har du rätt att ångra köpet inom 14 dagar från den dag du tar emot varorna, utan att ange någon orsak, med undantag för det som anges i informationen om ångerrätt.",
    "terms.withdrawal.services": "För tjänster, till exempel en bokning, löper de 14 dagarna från den dag avtalet ingicks.",
    "terms.withdrawal.regular": "För en prenumerationslåda (regelbunden leverans av varor) löper de 14 dagarna från den dag du tar emot den första leveransen.",
    "terms.withdrawal.link": "Läs informationen om ångerrätt och [använd ångerfunktionen]({href}).",
    "terms.withdrawal.nolink": "Läs informationen om ångerrätt på den här webbplatsen för att se hur du använder rätten.",
    "h.terms.returns_link": "Retur",
    "terms.returns.1": "Du kan returnera varor inom {days} dagar efter att du har tagit emot dem. Se returpolicyn för hur.",
    "terms.returns.shopper": "När du returnerar varor betalar du de direkta kostnaderna för att skicka tillbaka dem, om vi inte säger något annat.",
    "terms.returns.store": "Vi betalar kostnaden för att skicka returnerade varor tillbaka till oss.",
    "h.terms.conformity": "Fel på varan",
    "terms.conformity.1": "Varorna ska vara som avtalat. Om de inte är det har du de rättigheter som den lagstadgade garantin i ditt land ger dig. Rättigheterna gäller utöver det vi själva erbjuder.",
    "terms.conformity.2": "Reklamationstid: {check}",
    "h.terms.complaints": "Reklamation",
    "terms.complaints.1": "Om något är fel, skriv till oss på {email} så snart du upptäcker det.",
    "terms.complaints.2": "{check}",
    "h.terms.disputes": "Om vi inte kommer överens",
    "terms.disputes.1": "Om vi inte kommer överens om en reklamation kan du vända dig till {check}",
    "h.terms.privacy_link": "Personuppgifter",
    "terms.privacy.1": "Hur vi behandlar dina personuppgifter beskrivs i vår integritetspolicy.",
    "h.terms.bookings_subscriptions": "Bokningar och prenumerationslådor",
    "terms.bookings.1": "Besök, boenden och uthyrning bokas för en bestämd tid. Du kan avboka eller flytta en bokning fram till den tidsgräns som visas när du bokar.",
    "terms.bookings.2": "En prenumerationslåda levereras de dagar som visas och fortsätter tills du stoppar den. Du kan ändra, pausa eller avsluta den fram till den sista dag som visas före varje leverans.",
    "h.terms.businesses": "Köp av företag",
    "terms.business.1": "De här villkoren gäller också när ett företag köper av oss. Företag ser priser utan moms, men moms läggs till på beställningen där den gäller.",
    "terms.business.returns": "Den lagstadgade ångerrätten gäller konsumenter. För företag erbjuder vi retur av varor enligt returpolicyn.",
    "terms.business.noreturns": "Den lagstadgade ångerrätten gäller konsumenter och gäller inte när ett företag köper.",
    "h.terms.law_and_changes": "Lagval och ändringar",
    "terms.law.1": "De här villkoren regleras av lagen i {country}.",
    "terms.law.2": "{check}",
    "terms.law.3": "Vi kan ändra de här villkoren. Den version som gällde när du lade din beställning är den som gäller för den beställningen.",

    "h.privacy.controller": "Vem som är ansvarig",
    "privacy.controller.1": "{name}, organisationsnummer {org}, adress {address}, driver {store} och är personuppgiftsansvarig för de personuppgifter som beskrivs här.",
    "privacy.controller.2": "Butiken körs på plattformen Kaizen Store. Plattformen behandlar personuppgifter för vår räkning, som vårt personuppgiftsbiträde.",
    "h.privacy.contact": "Kontakt",
    "privacy.contact.1": "Frågor om dina personuppgifter: {email}. Telefon: {phone}.",
    "h.privacy.purposes_basis": "Vad vi använder uppgifterna till",
    "privacy.purposes.1": "Vi använder personuppgifter för de här ändamålen, vart och ett på den rättsliga grund som anges:",
    "privacy.purpose.orders": "att ta emot, ta betalt för, leverera och följa upp dina beställningar, och att bekräfta och skicka det du har köpt (fullgörande av avtalet)",
    "privacy.purpose.accounting": "att föra bokföring och spara de underlag som lagen kräver (rättslig förpliktelse)",
    "privacy.purpose.service": "att svara på dina frågor och reklamationer (fullgörande av avtalet, och vårt berättigade intresse av att ge god service)",
    "privacy.purpose.security": "att hålla butiken säker och förebygga bedrägeri och missbruk (vårt berättigade intresse)",
    "privacy.purpose.marketing": "att skicka marknadsföring med e-post, bara om du har tackat ja till det (samtycke)",
    "privacy.purpose.visits": "att räkna besök i butiken utan cookies, för att se hur den används; vi sparar ingen IP-adress och ingen webbläsaridentifierare (vårt berättigade intresse)",
    "h.privacy.recipients": "Vilka som får uppgifterna",
    "privacy.recipients.1": "Vi delar personuppgifter bara med dem som behöver dem:",
    "privacy.recipient.platform": "plattformen Kaizen Store, som driver butiken och behandlar uppgifter för vår räkning",
    "privacy.recipient.stripe": "Stripe, vår betaltjänstleverantör, som hanterar betalningar",
    "privacy.recipient.email": "den e-posttjänst som plattformen använder för att skicka orderbekräftelser och andra meddelanden till dig",
    "privacy.recipient.carriers": "fraktbolag som levererar dina varor: {carriers}",
    "privacy.recipient.carriers.none": "fraktbolag som levererar dina varor: {check}",
    "privacy.recipient.tool": "{tool}, som butiken bara laddar om du godkänner de tillhörande cookies",
    "privacy.recipient.authorities": "myndigheter, när lagen kräver att vi lämnar ut uppgifter",
    "h.privacy.transfers": "Överföring utanför EU/EES",
    "privacy.transfers.1": "Plattformen lagrar butikens data i EU. Några av mottagarna ovan kan behandla uppgifter på annat håll.",
    "privacy.transfers.2": "{check}",
    "h.privacy.retention": "Hur länge vi sparar uppgifterna",
    "privacy.retention.1": "Order- och bokföringsuppgifter sparas så länge lagen kräver: {check}",
    "privacy.retention.2": "Andra uppgifter sparas bara så länge vi behöver dem för det ändamål de samlades in för. Ett kundkonto sparas tills du tar bort det.",
    "h.privacy.rights": "Dina rättigheter",
    "privacy.rights.1": "Du har rätt att:",
    "privacy.right.access": "begära tillgång till de personuppgifter vi har om dig",
    "privacy.right.rectify": "få felaktiga uppgifter rättade",
    "privacy.right.erase": "få dina uppgifter raderade, där lagen tillåter det (underlag som vi måste spara enligt lag kan inte raderas förrän tiden har gått ut)",
    "privacy.right.restrict": "begära att användningen av dina uppgifter begränsas",
    "privacy.right.portability": "få dina uppgifter i ett vanligt format och få dem flyttade till en annan tjänst",
    "privacy.right.object": "invända mot behandling som grundar sig på vårt berättigade intresse",
    "h.privacy.consent_withdrawal": "Återkalla samtycke",
    "privacy.consent.1": "Där vi använder dina uppgifter för att du har samtyckt kan du när som helst återkalla samtycket. Det påverkar inte det vi gjorde innan du återkallade det.",
    "h.privacy.complaint_authority": "Klagomål till myndigheten",
    "privacy.complaint.1": "Du kan klaga på hur vi behandlar dina personuppgifter hos dataskyddsmyndigheten: {check}",
    "h.privacy.obligation_to_provide": "Måste du lämna uppgifterna?",
    "privacy.obligation.1": "Du måste lämna de uppgifter vi behöver för att ingå och leverera din beställning, som namn, adress och e-post. Utan dem kan vi inte genomföra köpet. Allt annat är frivilligt.",
    "h.privacy.automated_decisions": "Automatiserade beslut",
    "privacy.automated.1": "Vi fattar inga beslut om dig som enbart grundar sig på automatiserad behandling och som har rättsliga följder eller liknande betydande verkningar för dig.",
    "privacy.automated.chat": "Butiken har en chattassistent som använder artificiell intelligens för att svara på frågor utifrån butikens egen information. Det du skriver till den skickas till den AI-leverantör som butiken använder ({check}). Skriv inte känsliga personuppgifter till den.",
    "h.privacy.cookies_link": "Cookies",
    "privacy.cookies.link": "De cookies och liknande verktyg som butiken använder finns uppräknade på [sidan om cookies]({href}).",
    "privacy.cookies.nolink": "De cookies och liknande verktyg som butiken använder finns uppräknade på butikens sida om cookies.",

    "h.returns_policy.window": "Hur länge du har på dig",
    "returns.window.1": "Du kan returnera varor inom {days} dagar från den dag du tar emot dem.",
    "returns.window.extended": "Av dessa är 14 dagar din lagstadgade ångerrätt som konsument. Resten, upp till {days} dagar, är vår egen längre returtid, som vi erbjuder utöver det.",
    "h.returns_policy.how_to": "Så returnerar du",
    "returns.how.1": "Tala först om för oss att du vill returnera varor. Skicka sedan tillbaka dem enligt beskrivningen nedan.",
    "returns.how.instructions": "{instructions}",
    "returns.how.noinstructions": "{check}",
    "h.returns_policy.who_pays": "Vem som betalar för returen",
    "returns.pays.shopper": "Du betalar de direkta kostnaderna för att skicka tillbaka varorna, om inte varorna var felaktiga eller inte som avtalat.",
    "returns.pays.store": "Vi betalar kostnaden för att skicka tillbaka varorna.",
    "h.returns_policy.refund_timing": "När du får pengarna tillbaka",
    "returns.refund.received": "Vi betalar tillbaka det du har betalat, inklusive standardleverans, senast 14 dagar efter att vi har fått veta om ditt beslut. Vi kan vänta tills vi har fått tillbaka varorna, eller tills du har visat att du har skickat dem, beroende på vilket som inträffar först.",
    "returns.refund.request": "Vi betalar tillbaka det du har betalat, inklusive standardleverans, senast 14 dagar efter att vi har fått veta om ditt beslut.",
    "h.returns_policy.excluded_goods": "Varor som inte kan returneras",
    "returns.excluded.1": "Den lagstadgade ångerrätten gäller inte för:",
    "returns.excluded.accept": "Vi tar ändå tillbaka en del av de här varorna inom vår egen returtid, om de är i det skick vi ber om.",
    "returns.excluded.refuse": "Vi tar inte tillbaka de här varorna.",
    "h.returns_policy.return_address": "Vart returer skickas",
    "returns.address.1": "Skicka returer till: {address}.",
    "h.returns_policy.withdrawal_link": "Att ångra ett köp",
    "returns.withdrawal.link": "För att ångra ett köp som konsument, [använd ångerfunktionen]({href}) eller läs informationen om ångerrätt.",
    "returns.withdrawal.nolink": "För att ångra ett köp som konsument, läs informationen om ångerrätt på den här webbplatsen.",
    "h.returns_policy.businesses": "Köp av företag",
    "returns.business.1": "Den lagstadgade ångerrätten gäller konsumenter.",
    "returns.business.voluntary": "Företag kan returnera varor på samma sätt och inom samma tid som andra kunder, som en service från oss och inte som en lagstadgad rätt.",
    "returns.business.none": "Den gäller inte när ett företag köper, och vi tar inte tillbaka varor från företag om vi inte kommer överens om något annat.",

    "h.shipping_policy.markets": "Vart vi levererar",
    "shipping.markets.1": "Vi levererar till: {markets}.",
    "h.shipping_policy.rates": "Vad leveransen kostar",
    "shipping.rates.1": "Leveranskostnader, med moms, för varje land:",
    "shipping.rates.none": "Leveranskostnader: {check}",
    "h.shipping_policy.carriers": "Fraktbolag",
    "h.shipping_policy.delivery_time": "Hur lång tid det tar",
    "shipping.time.1": "Leveranstid: {check}",
    "h.shipping_policy.tracking": "Spårning",
    "shipping.tracking.1": "När din beställning har skickats får du ett e-postmeddelande. Där fraktbolaget erbjuder det innehåller meddelandet en spårningslänk.",
    "h.shipping_policy.outside_eu": "Utanför EU",
    "shipping.outside.1": "{check}",
    "h.shipping_policy.damaged_goods": "Skadade varor",
    "shipping.damaged.1": "Om varor kommer fram skadade, tala om det för oss {check}",
    "h.shipping_policy.contact": "Frågor",
    "shipping.contact.1": "Frågor om din leverans: {email}.",

    "h.withdrawal_info.right": "Ångerrätt",
    "withdrawal.right.1": "Om du är konsument har du rätt att frånträda det här avtalet inom 14 dagar utan att ange någon orsak.",
    "withdrawal.right.2": "Ångerfristen löper ut 14 dagar efter den dag då du, eller en tredje part som du har utsett och som inte är transportören, får varorna i fysisk besittning. Om du beställer flera varor i en beställning som levereras var för sig löper fristen ut 14 dagar efter den dag du tar emot den sista av dem.",
    "withdrawal.right.services": "För ett tjänsteavtal, till exempel en bokning, löper ångerfristen ut 14 dagar efter den dag avtalet ingicks.",
    "withdrawal.right.regular": "För ett avtal om regelbunden leverans av varor under en bestämd period, till exempel en prenumerationslåda, löper ångerfristen ut 14 dagar efter den dag du tar emot den första leveransen.",
    "h.withdrawal_info.how": "Så ångrar du dig",
    "withdrawal.how.1": "För att utöva ångerrätten måste du meddela {name}, {address}, {email}, att du frånträder avtalet, genom ett tydligt uttalande, till exempel i ett brev som skickas med post eller i ett e-postmeddelande.",
    "withdrawal.how.online": "Du kan också [ångra dig på webben]({href}) på den här webbplatsen.",
    "withdrawal.how.noonline": "Du kan också använda ångerfunktionen på den här webbplatsen.",
    "withdrawal.how.2": "Du kan använda modellblanketten nedan, men du måste inte. För att hålla fristen räcker det att du skickar ditt meddelande innan ångerfristen har löpt ut.",
    "h.withdrawal_info.effects": "Vad som händer när du ångrar dig",
    "withdrawal.effects.1": "Om du frånträder avtalet betalar vi tillbaka alla betalningar vi har fått från dig, inklusive kostnaderna för standardleverans, utan onödigt dröjsmål och senast 14 dagar efter den dag vi får veta om ditt beslut.",
    "withdrawal.effects.2": "Vi kan hålla inne återbetalningen tills vi har fått tillbaka varorna eller tills du har visat att du har skickat tillbaka dem, beroende på vilket som inträffar först. Vi använder samma betalningssätt som du använde vid beställningen, om du inte går med på något annat.",
    "withdrawal.effects.3": "Du måste skicka tillbaka varorna eller lämna dem till oss utan onödigt dröjsmål och senast 14 dagar efter den dag du meddelade oss att du ångrar dig.",
    "withdrawal.effects.pays.shopper": "Du betalar de direkta kostnaderna för att returnera varorna.",
    "withdrawal.effects.pays.store": "Vi betalar kostnaden för att returnera varorna.",
    "withdrawal.effects.4": "Du ansvarar bara för en eventuell värdeminskning på varorna som beror på annan hantering än den som är nödvändig för att fastställa varornas art, egenskaper och funktion.",
    "withdrawal.effects.services": "Om du har bett om att en tjänst ska påbörjas under ångerfristen ska du betala oss ett belopp som står i proportion till det som har tillhandahållits fram till dess att du meddelade oss att du ångrar dig, jämfört med avtalets hela omfattning.",
    "h.withdrawal_info.exclusions": "När det inte finns någon ångerrätt",
    "withdrawal.excl.1": "Det finns ingen ångerrätt för:",
    "h.withdrawal_info.model_form": "Modellblankett för ångerrätt",
    "withdrawal.form.1": "Fyll i och skicka in den här blanketten bara om du vill frånträda avtalet.",
    "withdrawal.form.to": "Till {name}, {address}, {email}:",
    "withdrawal.form.notice": "Jag/vi (*) meddelar härmed att jag/vi (*) frånträder mitt/vårt (*) avtal om köp av följande varor (*) / om tillhandahållande av följande tjänst (*),",
    "withdrawal.form.ordered": "Beställd den (*) / mottagen den (*),",
    "withdrawal.form.consumer": "Konsumentens/konsumenternas namn,",
    "withdrawal.form.address": "Konsumentens/konsumenternas adress,",
    "withdrawal.form.signature": "Konsumentens/konsumenternas underskrift (bara om blanketten skickas på papper),",
    "withdrawal.form.date": "Datum.",
    "withdrawal.form.note": "(*) Stryk det som inte är tillämpligt.",

    "h.imprint.legal_name": "Verksamhetens namn",
    "imprint.legal_name": "{name} (driver {store}).",
    "h.imprint.org_number": "Organisationsnummer",
    "imprint.org_number": "{org}.",
    "h.imprint.vat_number": "Moms",
    "imprint.vat.yes": "Momsregistreringsnummer: {vat}.",
    "imprint.vat.no": "Verksamheten är inte registrerad för moms.",
    "h.imprint.address": "Adress",
    "imprint.address": "{address}.",
    "h.imprint.email": "E-post",
    "imprint.email": "{email}.",
    "h.imprint.phone": "Telefon",
    "imprint.phone": "{phone}.",
    "h.imprint.register": "Register",
    "imprint.register": "{check}",
    "h.imprint.supervisory_authority": "Tillsynsmyndighet",
    "imprint.supervisory": "{check}",
  },
};
