-- The plan comparison (D132): the platform's list of features and which plan includes each.

ALTER TABLE commerce.plan_features ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint
ALTER TABLE commerce.plan_feature_grants ENABLE ROW LEVEL SECURITY;
--> statement-breakpoint

-- The features Kaizen has today, in no plan yet: the platform's admin ticks what each plan includes.
INSERT INTO commerce.plan_features (category, name, description, position) VALUES
  ('Storefront and catalogue', 'Products with variants and prices per market', 'Sizes, colours and any options, priced in each country you sell to.', 0),
  ('Storefront and catalogue', 'Digital products and downloads', 'Files sold as downloads, with download limits.', 10),
  ('Storefront and catalogue', 'Subscription products', 'Recurring orders with a chosen interval, trial and discount.', 20),
  ('Storefront and catalogue', 'Appointments and bookings', 'Sell time with staff, a calendar, deposits and reminders.', 30),
  ('Storefront and catalogue', 'Stays and rentals', 'Nights, days or hours, with seasons and calendar sync.', 40),
  ('Storefront and catalogue', 'Custom fields', 'Your own groups of fields on products, pages, categories and more.', 50),
  ('Storefront and catalogue', 'Categories, tags and product layouts', 'Organise the catalogue and design each product page.', 60),
  ('Storefront and catalogue', 'Search by meaning and filters', 'Keyword and AI search, with sorting and filters on every list.', 70),
  ('Storefront and catalogue', 'Customer reviews from Google', 'Show Google reviews on the store.', 80),
  ('Checkout and selling', 'Checkout with cards and local payment methods', 'Stripe Checkout on your own Stripe account.', 90),
  ('Checkout and selling', 'Discount codes', 'Percentage and fixed-amount codes with limits.', 100),
  ('Checkout and selling', 'Campaigns', 'Offers without a code: percentage off, buy N pay for M, free gifts.', 110),
  ('Checkout and selling', 'Customer groups and company accounts', 'Group discounts, business buyers and company employees.', 120),
  ('Checkout and selling', 'Selling to businesses', 'Prices without VAT for companies and company details at checkout.', 130),
  ('Checkout and selling', 'Abandoned cart reminders', 'Emails that bring shoppers back, with an optional code.', 140),
  ('Checkout and selling', 'Subscription boxes', 'Weekly deliveries from a standing list, charged when sent.', 150),
  ('Checkout and selling', 'Bonus credits', 'Customers earn credits on orders and use them later.', 160),
  ('Checkout and selling', 'Customer referrals', 'Customers refer friends: a welcome discount and credits for the referrer.', 170),
  ('Design and content', 'Page builder', 'Rows, columns and blocks for every page, with draft and publish.', 180),
  ('Design and content', 'Headers, footers and menus', 'Build the top and bottom of the site and its menus.', 190),
  ('Design and content', 'Design themes and fonts', 'Colours, buttons, cards and self-hosted Google Fonts.', 200),
  ('Design and content', 'Motion effects', 'Entrances, hover, scroll and background effects.', 210),
  ('Design and content', 'Pop-ups', 'Modals opened by a click, a timer or exit intent.', 220),
  ('Design and content', 'Blog', 'Articles with categories and tags.', 230),
  ('Design and content', 'Templates', 'Save rows and whole pages and share them with your other stores.', 240),
  ('Design and content', 'Custom CSS and code', 'Your own CSS and scripts on the site.', 250),
  ('Design and content', 'Forms and newsletter sign-up', 'Contact forms and sign-ups with email confirmation.', 260),
  ('Design and content', 'Media library', 'Every picture and video in one place, searchable.', 270),
  ('Design and content', 'Own domain', 'Your store at your own web address.', 280),
  ('International', 'Several countries and VAT', 'Sell to many EU countries with the right VAT.', 290),
  ('International', 'Languages and currencies', 'Show the store in several languages and currencies.', 300),
  ('International', 'AI translation of the whole store', 'Translations suggested by AI and checked by you.', 310),
  ('AI', 'AI manager', 'An assistant in the admin that answers from your data and acts with your yes.', 320),
  ('AI', 'Chat assistant for shoppers', 'A chat agent that answers from your store and its documents.', 330),
  ('AI', 'AI product texts', 'Suggested product descriptions in your words.', 340),
  ('AI', 'AI page studio', 'Describe a page and get a first draft.', 350),
  ('AI', 'Make my page cool', 'One click adds motion design to a page.', 360),
  ('AI', 'Picture descriptions by AI', 'Alt texts written for your pictures.', 370),
  ('AI', 'Your own AI provider', 'Use your own AI account and models.', 380),
  ('Operations', 'Orders, returns and refunds', 'Fulfil, refund and follow every order.', 390),
  ('Operations', 'Stock in several locations', 'Stock levels per location.', 400),
  ('Operations', 'Customer accounts and wish lists', 'Shoppers sign in, see their orders and save products.', 410),
  ('Operations', 'Emails to customers', 'Order emails in your shoppers'' languages.', 420),
  ('Operations', 'Staff accounts', 'Invite staff to help run the store.', 430),
  ('Operations', 'Hosts and commissions', 'List stays and rentals for other hosts and pay them.', 440),
  ('Operations', 'Work: time, tasks and invoicing', 'Clients, time tracking and invoices for your own services.', 450),
  ('Operations', 'Integrations and Slack', 'Webhooks and Slack messages for store events.', 460),
  ('Operations', 'Duplicate a store', 'Copy a store with the pages, products and settings you choose.', 470),
  ('Operations', 'Analytics and cookie consent', 'Your analytics tools, loaded only after consent.', 480),
  ('Kaizen', 'Refer other store owners', 'Earn credit on your plan from stores you refer.', 490);
