-- The areas of the activity log learn the redirects of wave 2 (D168): a redirect made, changed, deleted or imported, and an address hidden from the
-- 404 report are Website's. The same table as src/lib/audit.ts, which a test holds equal to this function (the whole function is replaced; a new
-- migration, never an edit of the one before).
CREATE OR REPLACE FUNCTION commerce.audit_area_of(p_action text) RETURNS text
LANGUAGE sql IMMUTABLE SET search_path = '' AS $$
  SELECT CASE
    WHEN p_action = 'shipping.bring_booked' THEN 'orders'
    WHEN p_action = 'shipping.helthjem_booked' THEN 'orders'
    WHEN p_action = 'shipping.porterbuddy_booked' THEN 'orders'
    WHEN p_action = 'company.office_saved' THEN 'settings'
    WHEN p_action = 'store.bonus_settings' THEN 'marketing'
    WHEN p_action = 'store.affiliate_settings' THEN 'marketing'
    WHEN p_action = 'store.fields_updated' THEN 'website'
    WHEN p_action = 'store.ai_translated' THEN 'website'
    WHEN p_action = 'store.front_page_changed' THEN 'website'
    WHEN p_action = 'store.products_page_changed' THEN 'website'
    WHEN p_action = 'store.page_role_changed' THEN 'website'
    WHEN p_action = 'store.legal_role_changed' THEN 'website'
    WHEN p_action = 'store.navigation_updated' THEN 'website'
    WHEN p_action = 'store.part_sharing' THEN 'website'
    WHEN p_action = 'invoice.settings_updated' THEN 'settings'
    WHEN p_action = 'invoice.series_set' THEN 'settings'
    WHEN p_action = 'activity.exported' THEN 'staff'
    WHEN p_action = 'store.two_step_required' THEN 'staff'
    WHEN p_action = 'store.two_step_optional' THEN 'staff'
    WHEN p_action = 'store.legal_starter_made' THEN 'website'
    WHEN starts_with(p_action, 'store.product_layout_') THEN 'products'
    WHEN starts_with(p_action, 'store.products_page_') THEN 'website'
    WHEN starts_with(p_action, 'store.saved_theme_') THEN 'website'
    WHEN starts_with(p_action, 'booking_resource.') THEN 'bookings'
    WHEN starts_with(p_action, 'store.front_page_') THEN 'website'
    WHEN starts_with(p_action, 'google.platform_') THEN 'platform'
    WHEN starts_with(p_action, 'recommendations.') THEN 'marketing'
    WHEN starts_with(p_action, 'cart_reminders.') THEN 'marketing'
    WHEN starts_with(p_action, 'plan_reminders.') THEN 'platform'
    WHEN starts_with(p_action, 'product_layout.') THEN 'products'
    WHEN starts_with(p_action, 'resource_block.') THEN 'bookings'
    WHEN starts_with(p_action, 'store.template_') THEN 'website'
    WHEN starts_with(p_action, 'store.two_step_') THEN 'staff'
    WHEN starts_with(p_action, 'calendar_feed.') THEN 'bookings'
    WHEN starts_with(p_action, 'company.place_') THEN 'settings'
    WHEN starts_with(p_action, 'store.article_') THEN 'website'
    WHEN starts_with(p_action, 'localization.') THEN 'settings'
    WHEN starts_with(p_action, 'store.footer_') THEN 'website'
    WHEN starts_with(p_action, 'store.header_') THEN 'website'
    WHEN starts_with(p_action, 'ai.platform_') THEN 'platform'
    WHEN starts_with(p_action, 'credit_note.') THEN 'orders'
    WHEN starts_with(p_action, 'field_group.') THEN 'website'
    WHEN starts_with(p_action, 'integration.') THEN 'settings'
    WHEN starts_with(p_action, 'search_test.') THEN 'marketing'
    WHEN starts_with(p_action, 'store.fonts_') THEN 'website'
    WHEN starts_with(p_action, 'store.media_') THEN 'website'
    WHEN starts_with(p_action, 'store.theme_') THEN 'website'
    WHEN starts_with(p_action, 'deliveries.') THEN 'orders'
    WHEN starts_with(p_action, 'experiment.') THEN 'marketing'
    WHEN starts_with(p_action, 'store.menu_') THEN 'website'
    WHEN starts_with(p_action, 'store.page_') THEN 'website'
    WHEN starts_with(p_action, 'store.part_') THEN 'website'
    WHEN starts_with(p_action, 'analytics.') THEN 'analytics'
    WHEN starts_with(p_action, 'knowledge.') THEN 'settings'
    WHEN starts_with(p_action, 'not_found.') THEN 'website'
    WHEN starts_with(p_action, 'redirects.') THEN 'website'
    WHEN starts_with(p_action, 'retention.') THEN 'platform'
    WHEN starts_with(p_action, 'store.css_') THEN 'website'
    WHEN starts_with(p_action, 'bookings.') THEN 'bookings'
    WHEN starts_with(p_action, 'campaign.') THEN 'marketing'
    WHEN starts_with(p_action, 'customer.') THEN 'customers'
    WHEN starts_with(p_action, 'discount.') THEN 'marketing'
    WHEN starts_with(p_action, 'document.') THEN 'orders'
    WHEN starts_with(p_action, 'language.') THEN 'platform'
    WHEN starts_with(p_action, 'payments.') THEN 'settings'
    WHEN starts_with(p_action, 'platform.') THEN 'platform'
    WHEN starts_with(p_action, 'products.') THEN 'products'
    WHEN starts_with(p_action, 'redirect.') THEN 'website'
    WHEN starts_with(p_action, 'shipping.') THEN 'settings'
    WHEN starts_with(p_action, 'account.') THEN 'account'
    WHEN starts_with(p_action, 'article.') THEN 'website'
    WHEN starts_with(p_action, 'billing.') THEN 'billing'
    WHEN starts_with(p_action, 'booking.') THEN 'orders'
    WHEN starts_with(p_action, 'company.') THEN 'customers'
    WHEN starts_with(p_action, 'cookies.') THEN 'settings'
    WHEN starts_with(p_action, 'invoice.') THEN 'orders'
    WHEN starts_with(p_action, 'privacy.') THEN 'customers'
    WHEN starts_with(p_action, 'product.') THEN 'products'
    WHEN starts_with(p_action, 'returns.') THEN 'settings'
    WHEN starts_with(p_action, 'footer.') THEN 'website'
    WHEN starts_with(p_action, 'google.') THEN 'settings'
    WHEN starts_with(p_action, 'header.') THEN 'website'
    WHEN starts_with(p_action, 'return.') THEN 'orders'
    WHEN starts_with(p_action, 'hosts.') THEN 'bookings'
    WHEN starts_with(p_action, 'order.') THEN 'orders'
    WHEN starts_with(p_action, 'staff.') THEN 'staff'
    WHEN starts_with(p_action, 'store.') THEN 'settings'
    WHEN starts_with(p_action, 'chat.') THEN 'settings'
    WHEN starts_with(p_action, 'host.') THEN 'bookings'
    WHEN starts_with(p_action, 'page.') THEN 'website'
    WHEN starts_with(p_action, 'role.') THEN 'staff'
    WHEN starts_with(p_action, 'site_') THEN 'website'
    WHEN starts_with(p_action, 'term.') THEN 'website'
    WHEN starts_with(p_action, 'tier.') THEN 'customers'
    WHEN starts_with(p_action, 'work.') THEN 'settings'
    WHEN starts_with(p_action, 'vat.') THEN 'platform'
    WHEN starts_with(p_action, 'ai.') THEN 'settings'
    ELSE 'settings'
  END
$$;
